### ISSUE TITLE
All application icons stay when searching

### ISSUE THREAD

**Issue by 0x24D** [subgraph/subgraph-os-issues#100]
I have just upgraded all my packages and whenever I search for any application, say tor-browser for example, it shows the tor-browser icon at the top but the list of all the installed application remains on the screen.
![virtualbox_subgraph_11_03_2016_00_55_00](https://cloud.githubusercontent.com/assets/8465663/13689895/3063a3b2-e724-11e5-9df1-67c20a1be23e.png)

**Comment by xSmurf** [comment]
Does this persist after a reboot or a session logout/login cycle?

**Comment by 0x24D** [comment]
I've just tried again and it now works as expected, thanks anyway.
