### ISSUE TITLE
CoyIM Messenger - version outdated in current alpha, includes bugs

### ISSUE THREAD

**Issue by RooneyMcNibNug** [subgraph/subgraph-os-issues#105]
HI,

I have experienced an issue with CoyIM on the latest alpha available for download. The issue was patched in the latest update for Coy itself, but it seems the version currently loaded within SubgraphOS alpha is an outdated one. 

(please see @xSmurf 's comment at https://github.com/twstrike/coyim/issues/278)

Thanks,
- RooneyMcNibNug

**Comment by xSmurf** [comment]
We looked at building a new package this morning but the tests are currently broken, we'll have a bit more back and forth to do with the CoyIM team (cc @olabini )

**Comment by xSmurf** [comment]
I've opened an issue with the CoyIM about the tests: https://github.com/twstrike/coyim/issues/281

**Comment by RooneyMcNibNug** [comment]
I'm going to go ahead and close this now, as it seems to be completely gone with the latest update.
Thanks.
