### ISSUE TITLE
Live startup from USB stick stalled

### ISSUE THREAD

**Issue by willscott** [subgraph/subgraph-os-issues#11]
Installation worked, but the live boot (first option on the grub menu) left the computer with a blinking white cursor on an otherwise black screen. On a [celeron N3050](http://www.acer.com/ac/en/US/content/model/DT.B28AA.001). No useful diagnostic information printed.

**Comment by mckinney-subgraph** [comment]
Hi,

You can gather some diagnostics by doing changing the boot options. This is how to do it:
1. Press `TAB` from the boot menu
2. Remove the `splash` option
3. Add the `debug=1` option

![live_debug](https://cloud.githubusercontent.com/assets/3606565/12762746/af28e21c-c9be-11e5-918e-e93cab2290af.png)

**Comment by willscott** [comment]
Same behavior with the different boot options, I think I edited them
correctly.

On the 'failsafe' live boot I see 3 messages and then also get a hang:
* loading kernel
* loading initrd
<screen clears>
Probing EDD (edd=off to disable)...

**Comment by xSmurf** [comment]
@willscott Does this still happen on your hardware with the latest release?

**Comment by willscott** [comment]
Yes. this works on the latest release
