### ISSUE TITLE
Name resolving error during the PGP keys upload to keyserver

### ISSUE THREAD

**Issue by pietrearby** [subgraph/subgraph-os-issues#112]
After allowing Seahorse access to keyservers

![fwrls](https://cloud.githubusercontent.com/assets/17863703/13950199/e6eb67ce-f029-11e5-8720-e9e511cabcba.png)

the upload failed due to name resolving error

![dbmssg](https://cloud.githubusercontent.com/assets/17863703/13950219/f8be705e-f029-11e5-9f65-03cebb8ae9f3.png)

**Comment by xSmurf** [comment]
Odd I just tried and it worked fine for me, can you show me the contents of `/etc/resolv.conf` ?

**Comment by pietrearby** [comment]
`nameserver 127.0.0.1`

It's inside of VirtualBox, sorry I forgot to mention that but everything else is working.

**Comment by pietrearby** [comment]
@xSmurf I can't explain it but suddenly it works and I did nothing at all. The only thing I can think of is that it could be related to the fact it was first publish/sync and fw was not set up yet. I'll try it on other installation and if not reproducible you can close it and file it to X-Files.

**Comment by xSmurf** [comment]
Could be a bad Tor circuit as well maybe?

Let me know how that goes :)

**Comment by pietrearby** [comment]
@xSmurf I tried on different (also up-to-date) instalation three different tor circuits with three different fw settings once/session/forever and I can't reproduce it. So you can safely close it I guess.

**Comment by xSmurf** [comment]
Thanks for the testing and coming back to me :)
