### ISSUE TITLE
Document sandboxing effort for Ricochet

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#116]
This is a ticket to document the process by which we sandbox `ricochet` - we first write an `oz-daemon` policy for containment, then we write a seccomp filter list, we enable it and then we use ricochet inside of oz, fully contained. These steps can be applied to nearly any application that needs to be sandboxed with `oz`. This is using an experimental branch of ricochet that uses unix sockets and other neat stuff.

First, create a seccomp filter list like so:
`oz-seccomp-tracer -train -output /tmp/ricochet-filter-allowlist.seccomp /usr/bin-oz/app 2>/tmp/syscalls-output.txt`

Exercise all of the available options, flip different switches, add a buddy, get added by someone, etc. I did this, exited `ricochet` and then did it a few more times. In the end, I gathered all of my seccomp files and made a single file with only the unique entries.

I created a `ricochet.json` `oz` policy:

```
{
"path": "/usr/bin/ricochet"
, "allowed_groups": ["debian-tor"]
, "xserver": {
    "enabled": true
    , "enable_tray": false
    , "audio_mode": "pulseaudio"
}
, "networking":{
    "type":"empty"
    , "sockets": [
        {"type":"client", "proto":"tcp", "port":9050}
        , {"type":"client", "proto":"tcp", "port":9051}
    ]
}i
, "whitelist": [
        {"path":"${HOME}/.config/ricochet", "can_create":true}
        , {"path":"${HOME}/.local/share/Ricochet", "can_create":true}
#       , {"path":"/run/shm/service", "can_create":true}
        , {"path":"/run/tor/control", "can_create":false}
        , {"path":"/var/lib/oz/cells.d/ricochet-whitelist.seccomp"}

]
, "environment": [
    {"name":"TOR_CONTROL_PORT"}
]
, "seccomp": {
        "mode":"whitelist"
        , "whitelist":"/var/lib/oz/cells.d/ricochet-whitelist.seccomp"
        , "enforce": true
}
}
```

Then I've created  `ricochet.json` into `/var/lib/oz/cells.d/` and moved `/tmp/ricochet-filter-allowlist.seccomp` into  `/var/lib/oz/cells.d/` like so:

```
mv /tmp/ricochet-filter-allowlist.seccomp /var/lib/oz/cells.d/ricochet-whitelist.seccomp
```

Next up - we'll enable `oz` for `ricochet` like so:

```
oz-setup install ricochet
```

We'll need to set a pax flag unless you have a working ricochet Debian install (you probably don't!):

```
setfattr -n user.pax.flags -v "emr" /usr/bin-oz/ricochet 
```

If you want to disable it and trace again for seccomp filters you've missed:

```
oz-setup remove ricochet
```

(I also had to add `debian-tor:x:111:user` to my `/etc/groups` file.)

**Comment by ioerror** [comment]
I've also modified the above to be:
```
, "whitelist": [
        {"path":"${HOME}/.config/ricochet", "can_create":true}
        , {"path":"${HOME}/.local/share/Ricochet", "can_create":true}
        , {"path":"/home/user/.local/share/Ricochet/service", "can_create":true}
        , {"path":"/run/tor/control", "can_create":false}
        , {"path":"/var/lib/oz/cells.d/ricochet-whitelist.seccomp"}

]
```

I've had to fixup Tor's AppArmor profile to allow it to read and write to ```/home/user/.local/share/Ricochet/service``` for Ricochet's Tor HS.

Also, as a side note, I have 82 entries in ```ricochet-whitelist.seccomp``` which is a nice reduction of total available system calls.

**Comment by burdges** [comment]
Just commenting to watch

**Comment by ioerror** [comment]
My seemingly functional ```ricochet-whitelist.seccomp``` is:
```
accept4:1
access:1
arch_prctl:1
bind:1
brk:1
capget:1
chdir:1
chmod:1
clock_getres:1
clone:1
close:1
connect:1
dup2:1
epoll_wait:1
eventfd2:1
execve:1
exit:1
exit_group:1
fadvise64:1
fcntl: arg1 == 2 || arg1 == 3 || arg1 == 4 || arg1 == 6 || arg1 == 1 
fdatasync:1
flock:1
fstat:1
fstatfs:1
ftruncate:1
futex: arg1 == 129 || arg1 == 128 || arg1 == 133 || arg1 == 134 || arg1 == 135 || arg1 == 132 || arg1 == 137 || arg1 == 0 
getcwd:1
getdents:1
getegid:1
geteuid:1
getgid:1
getpeername:1
getrandom:1
getresgid:1
getresuid:1
getrlimit:1
getsockname:1
getsockopt:1
gettid:1
getuid:1
inotify_add_watch:1
ioctl: arg1 == 2147771394 || arg1 == 2148557923 || arg1 == 3222299718 || arg1 == 3222299739 || arg1 == 3222299745 || arg1 == 1074291721 || arg1 == 3222299761 || arg1 == 3222824050 || arg1 == 3223872606 || arg1 == 1074553951 || arg1 == 3221775469 || arg1 == 3222299748 || arg1 == 1074029664 || arg1 == 1077961833 || arg1 == 3222299659 || arg1 == 3222299746 || arg1 == 3222037606 || arg1 == 1074291822 || arg1 == 21531 || arg1 == 3221775447 || arg1 == 35111 || arg1 == 1075864669 || arg1 == 25688 
ionotify_intit1:1
kill:1
link:1
listen:1
lseek:1
lstat:1
madvise:1
mkdir:1
mmap:1
mprotect:1
mremap:1
munmap:1
open:1
openat:1
pipe:1
pipe2:1
poll:1
prctl: arg0 == 15 
pselect6:1
read:1
readlink:1
readlinkat:1
recvfrom:1
recvmsg:1
rename:1
restart_syscall:1
rmdir:1
rt_sigaction:1
rt_sigprocmask:1
sched_getaffinity:1
select:1
sendmsg:1
sendto:1
set_robust_list:1
setsid: 1
setsockopt: arg2 == 10 || arg2 == 12 || arg2 == 8 || arg2 == 7 || arg2 == 16 
set_tid_address:1
shmat:1
shmctl:1
shmdt:1
shmget:1
shutdown:1
socket: arg0 == 1 || arg0 == 2 || arg0 == 16 
stat:1
statfs:1
uname:1
unlink:1
wait4:1
write:1
writev:1
```
My seemingly functional ```ricochet.json``` is:
```
{
"path": "/usr/bin/ricochet"
, "allowed_groups": ["debian-tor"]
, "xserver": {
	"enabled": true
	, "enable_tray": false
	, "audio_mode": "pulseaudio"
}
, "networking":{
	"type":"empty"
	, "sockets": [
		{"type":"client", "proto":"tcp", "port":9050}
		, {"type":"client", "proto":"tcp", "port":9051}
	]
}
, "whitelist": [
	{"path":"${HOME}/.config/ricochet", "can_create":true}
	, {"path":"${HOME}/.local/share/Ricochet", "can_create":true}
	, {"path":"/home/user/.local/share/Ricochet/service", "can_create":true}
	, {"path":"/run/tor/control", "can_create":false}
        , {"path":"/var/lib/oz/cells.d/ricochet-whitelist.seccomp"}

]
, "environment": [
	{"name":"TOR_CONTROL_PORT"}
]
, "seccomp": {
        "mode":"whitelist"
        , "whitelist":"/var/lib/oz/cells.d/ricochet-whitelist.seccomp"
        , "enforce": true
}
}
```

**Comment by david415** [comment]
i started to add a tor control port filter daemon ruleset for richochet but i didn't finish it yet; here's the ticket:
https://github.com/subgraph/roflcoptor/issues/8

**Comment by david415** [comment]
ok all the above sounds good but there is a critical component missing;

How does ricochet receive incoming connections from the tor process to it's onion service listener inside the oz jail cell?

If I am not mistaken at this time, it doesn't. It simply will not work because of this.

What I think we need to do is have oz provide a unix domain socket listener which provides an RPC service. This RPC would allow roflcoptor (the tor control port filter daemon) to add or remove oz proxy channels dynamically. Roflcoptor would then issue these RPC requests when it receives either an ADD_ONION or DEL_ONION command from the application using the control port.

**Comment by david415** [comment]
btw the above connectivity problem is also going to be an issue for onionshare and any other application that expects to use the onion service it just created.

**Comment by xSmurf** [comment]
Again, thanks to @david415 & @dma's great work everything is now upstream, now we need a Ricochet package.

**Comment by xSmurf** [comment]
Ricochet is now fully working OOTB! Thanks to everyone for all their efforts! :100: :tada:
