### ISSUE TITLE
clipboard for TBB

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#118]
My clipboard in TBB with ```oz``` is going nuts:
```
Mar 23 18:44:35 subgraph oz-daemon[23418]: 2016/03/23 18:44:35 [torbrowser-launcher] (xpra-server) 2016-03-23 18:44:35,716 clipboard disabled: more than 20 clipboard requests per second!
Mar 23 18:44:35 subgraph oz-daemon[23418]: 2016/03/23 18:44:35 [torbrowser-launcher] (xpra-client-stderr) 2016-03-23 18:44:35,717 clipboard toggled to off by the server, reason: more than 20 clipboard requests per second!
```

Anyone else?

**Comment by pietrearby** [comment]
I managed to reproduce the same result. But it was after frenzy copy/paste race between the tor browser, gedit and Libre Office Writer if that counts.

**Comment by xSmurf** [comment]
Duplicate of #81 and https://github.com/subgraph/oz/issues/26

**Comment by dma** [comment]
Fixed by https://github.com/subgraph/oz/commit/320ed99b57fd552273876285c5a3f8686259ef9e.
