### ISSUE TITLE
Add transmission

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#12]
I would like to be able to use bittorrent safely - it would be nice if Transmission was contained by oz and then routed over Tor safely for downloading debian iso files.

**Comment by mckinney-subgraph** [comment]
It is possible to use Transmission over a VPN:
[Creating an OpenVPN Sandbox for Transmission](https://subgraph.com/sgos/documentation/openvpn-transmission/)

Configuring to use Tor instead seems pretty trivial too. Closing issue.
