### ISSUE TITLE
Tor browser default download directory UX problem

### ISSUE THREAD

**Issue by pietrearby** [subgraph/subgraph-os-issues#122]
When typical non-tech user downloads file with Tor Browser, it's very hard for him/her to locate it.

Either it is buried in `~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/Downloads/` which is **not visible in default nautilus setting** or he/she can save it to `~/Downloads/` where it is **visible to Tor Browser only** and even that only as long as Tor Browser is not closed.

**Comment by xSmurf** [comment]
This is a property of TBBL which we currently cannot address. This should be fixed once we have a proper package for TBB as noted in #18. Meanwhile, `~/Downloads/TorBrowser` is shared with the host, anything saved there will be available outside of the sandbox.

I'll close the ticket for now as this will be addressed once the package is ready.
