### ISSUE TITLE
Gnome locks up with heavy Tor load

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#131]
I've found that when Tor is using 100% of my CPU for ~10 minutes at a time - Gnome completely locks up. During this time, I'll find that gnome is segfaulting depending on different interactions:

```
Apr  4 11:42:32 subgraph kernel: [143614.902712] gnome-shell[1198]: segfault at 1f86fd5c60 ip 0000031549cee4fc sp 000003fe19907660 error 4 in libmutter.so.0.0.0[31549c68000+fc000]
Apr  4 14:15:22 subgraph kernel: [ 1651.665423] gnome-shell[1224]: segfault at e0 ip 000003f44851e4c0 sp 000003fea24e68c8 error 4 in libclutter-1.0.so.0.2400.2[3f448490000+155000]
Apr  4 14:15:31 subgraph kernel: [ 1660.055195] gnome-shell[3000]: segfault at fffffffd6fad72c0 ip 000003d9afb916a5 sp 000003fe25a2ff30 error 5 in libmutter.so.0.0.0[3d9afb02000+fc000]
Apr  4 14:30:21 subgraph kernel: [ 2550.882692] gnome-shell[3202]: segfault at 1a6ff4d510 ip 0000032b3e28d4fc sp 000003ff54a3a4e0 error 4 in libmutter.so.0.0.0[32b3e207000+fc000]
Apr  4 14:40:06 subgraph kernel: [ 3135.274620] gnome-shell[5272]: segfault at e0 ip 0000036ce3dd74c0 sp 000003fedf14e398 error 4 in libclutter-1.0.so.0.2400.2[36ce3d49000+155000]
Apr  4 14:40:14 subgraph kernel: [ 3143.918658] gnome-shell[6077]: segfault at 1c37384030 ip 00000361423d34fc sp 000003fc1273c0b0 error 4 in libmutter.so.0.0.0[3614234d000+fc000]
```

I think that this is because the Tor control port is locking the gnome-shell with the "Tor Network" extension. I found that if I turn off the Tor Control port entirely, resume activity to heavily load Tor and Gnome shell lags a bit - but not a full lock up.

I suspect that this Tor extension is not able to handle whatever is happening (or not happening) on the Tor Control Port. It may be something else entirely as well.

**Comment by DonnchaC** [comment]
👍 I'm seeing this happening too with high Tor load

**Comment by xSmurf** [comment]
Should be improved in newer release of the status extension, any chance you could replicate?

**Comment by xSmurf** [comment]
No reports since updates, I'm considering it closed. Feel free to re-open if there are other reports!
