### ISSUE TITLE
Install python-txtorcon

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#133]
It would be nice to have ```python-txtorcon``` installed by default.

**Comment by ioerror** [comment]
```python-txtorcon``` will allow us to write a gnome-shell extension to easily share a file as an arbitrary onion. Docs here: http://timaq4ygg2iegci7.onion/

**Comment by ioerror** [comment]
We'll need to have 0.14.2-1 from unstable migrate to testing before this will work, I think.

**Comment by xSmurf** [comment]
Is it necessary to have this added as default? If an extension is written its package can declare it a dependency...

**Comment by brl** [comment]
This is not the right tool for the project you describe.  Soon we're going to write a daemon which exports a dbus interface to Tor control functionality and then later we're going to integrate file sharing into Nautilus.
