### ISSUE TITLE
sha256sum Error

### ISSUE THREAD

**Issue by Ioniangraphics** [subgraph/subgraph-os-issues#138]
Upon following the instructions on your install page, the following results occur:

sha256sum -c subgraph-os-alpha_2016-03-11_1.iso.sha256
subgraph-os-alpha_2016-03-11_1.iso: OK
sha256sum: **WARNING: 1 line is improperly formatted**

**Comment by xSmurf** [comment]
Hi @Ioniangraphics, we know about this issue, I understand it's a little bit scary but as it is a non-fatal warning and doesn't actually prevent one from verifying the shasum this won't get fixed until we release a new image.
