### ISSUE TITLE
Use Linux-libre kernel instead of Linux kernel

### ISSUE THREAD

**Issue by sampablokuper** [subgraph/subgraph-os-issues#140]
The Linux kernel contains [non-free](https://en.wikipedia.org/w/index.php?title=Free_software&oldid=695656324#Definition_and_the_Four_Freedoms) BLOBs. Because these binaries may run with kernel privileges and cannot be readily audited, they might undermine the security of Subgraph OS.

Please use the [Linux-libre kernel](https://en.wikipedia.org/wiki/Linux-libre) instead.

**Comment by xSmurf** [comment]
Hardware support is currently more important. If you hardware is FLOSS feel free to remove the firmware blobs.

There was already an issue for this with a discussion about this ( #77 ); but somehow it got deleted.
