### ISSUE TITLE
Provide an installation image of subgraphOS

### ISSUE THREAD

**Issue by jjaone** [subgraph/subgraph-os-issues#141]
Please, provide an installation image(s) and howto-instructions on which platforms and architecturs Subgraph is targeting and what are the hw requirements to use SubgraphOS. Specifically I'd like to know does Subgraph support ARMv7 and ARMv8 32/64-bit architectures and is Wayland/Mir/X11 all and mobile (embedded) Linux systems supported? Thanks for any info :)

**Comment by xSmurf** [comment]
This is all available here: https://subgraph.com/sgos/download/.

Some ARM support is planned for the future.
