### ISSUE TITLE
Icedove not working after a dist-upgrade

### ISSUE THREAD

**Issue by subproc** [subgraph/subgraph-os-issues#142]
after the dist-upgrade if i launch icedove start the sandbox but icedove it's unusable 'cause there's no graphical interface.
System log say:
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] xpra work dir is /home/user/.Xoz/icedove
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] Starting xpra server
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] (xpra-server) I /usr/bin/xpra [/usr/bin/xpra --no-daemon --mmap --no-sharing --bell --system-tray --xsettings --cursors --encoding=rgb --clipboard --no-microphone --no-speaker --no-notifications --no-mdns --input-method=keep --socket-dir=/home/user/.Xoz/icedove start :0]
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] (xpra-server) Warning: invalid option: 'scaling'
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] (xpra-server) Warning: invalid option: 'html'
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] (xpra-server) WARNING: low display number: 0
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] (xpra-server) You are attempting to run the xpra server against what seems to be a default X11 display ':0'.
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] (xpra-server) This is generally not what you want.
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] (xpra-server) You should probably use a higher display number just to avoid any confusion (and also this warning message).
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] (xpra-server) 2016-05-01 14:06:21,846
May  1 14:06:21 subgraph kernel: [  552.019418] audit_printk_skb: 168 callbacks suppressed
May  1 14:06:21 subgraph kernel: [  552.019421] audit: type=1326 audit(1462104381.839:68): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=13079 comm="Xorg" exe="/usr/lib/xorg/Xorg" sig=31 arch=c000003e syscall=165 compat=0 ip=0x3894d3ba66a code=0x0
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] (xpra-server) 2016-05-01 14:06:21,846 Xvfb command has terminated! xpra cannot continue
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] (xpra-server) 2016-05-01 14:06:21,846  if the display is already running, try a different one,
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] (xpra-server) 2016-05-01 14:06:21,846  or use the --use-display flag
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] (xpra-server) 2016-05-01 14:06:21,846
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] (xpra-server) 2016-05-01 14:06:21,847 removing socket /home/user/.Xoz/icedove/icedove-0
May  1 14:06:21 subgraph oz-daemon[813]: 2016/05/01 14:06:21 [icedove] Child process pid=10 exited from init with status 1

**Comment by dma** [comment]
I believe this is fixed by this: https://github.com/subgraph/oz/commit/1e5ef786adbc4f921d52f3f66ee27acd73c944b2. Can you try? Add pread64:1 to your /var/lib/oz/cells.d/icedove-whitelist.seccomp, then kill the icedove sandbox, and re-open it.

**Comment by subproc** [comment]
i'm going to close this issues because after another dist-upgrade icedove is working flawlessly...
thanks..
