### ISSUE TITLE
Can't login since last "apt-get update" 

### ISSUE THREAD

**Issue by DamirRT** [subgraph/subgraph-os-issues#146]
Hi,

i'm running subgraph in an virtualbox (actual version).
yesterday (24.05.2016) i have made an sudo update / upgrade.

After reboot the login isn't possible

The login screen shows my user , i chose the user and fill my pwd
then the window get black with a red line (i suppose this is red text) 
after this ... the login screen shows up

anyone with the same issue / problem ?

Greetings
DamirRT

**Comment by xSmurf** [comment]
This should be fixed for the last few days with the new session package update, go to a console via "ctrl-alt-f2" and run updates again. Sorry we didn't catch this change with GNOME 3.20 earlier :\

**Comment by pabit** [comment]
Try downgrade Nvidia drivers if you have nvidia card.
