### ISSUE TITLE
'Tap to click' and natural scrolling options unavailable since last upgrade and dist-upgrade. Screen dims or goes blank every once in a while.

### ISSUE THREAD

**Issue by gdrdrposteo** [subgraph/subgraph-os-issues#147]
Hello!

Before the last successful upgrade and dist-upgrade, I had 'tap to click' and natural scrolling working, Screen also doesn't suddenly go blank every once in a while. All of those untrue anymore. The options to even enable/disable them aren't there anymore. I've attached a screenshot. 
![screenshot from 2016-06-02 10-02-30](https://cloud.githubusercontent.com/assets/19703363/15736601/5030ef08-2890-11e6-865c-c559c52b6493.png)
What could have happened? Help please? 

Thanks!

**Comment by mckinney-subgraph** [comment]
Workarounds for the missing mouse settings can be found here:
https://readlist.com/lists/lists.debian.org/debian-user/74/373604.html

This is a change with Gnome 3.20 on Debian Stretch (which Subgraph OS is based off of). It seems they may find some way of addressing it upstream at some point.

**Comment by xSmurf** [comment]
Seems fixed upstream, closing.
