### ISSUE TITLE
can't use TBB after dist-upgrade

### ISSUE THREAD

**Issue by subproc** [subgraph/subgraph-os-issues#148]
today i've installed sgos on another pc, but after an update/dist-upgrade and later the download of the TBB, i can start it..the sandbox for tor browser launcher start but nothing system log say pax is killing it...how to do?

**Comment by subproc** [comment]
it say 
PAX: execution attempt in: <anonymous mapping>, 3a822dbc000-3a822dcc000 3a822dbc000
PAX: terminating task: /home/user/.local/share/torbrowser....
PAX: bytes at PC: 55 48 8b ec 53 41 54 41 55 41 56 41 57 ff 75 18 4c 8b f4 4c


and then:
grsec: denied resourceboverstep by requesting 4096 for RLIMIT_CORE against limit 0 for /srv/oz/rootfs/home/user/.local/share/torbrowser.....

**Comment by gdrdrposteo** [comment]
Aha I thing I had this same issue last night. Hold on lemme check my chat logs.

**Comment by subproc** [comment]
Looking inside older issues i find the solution in #54...so, seems that paxrat doesn't work well on new/updated package....but now it's all fine...i can use tbb...

**Comment by gdrdrposteo** [comment]
I think a fix regarding TBB in this link also can be an answer to your 
issue? https://subgraph.com/sgos/download/notes/

**Comment by gdrdrposteo** [comment]
I assume this https://github.com/subgraph/subgraph-os-issues is intended as a start to learn about Subgraph OS especially issues?
