### ISSUE TITLE
Unable to login my Dukgo account in Coy IM.

### ISSUE THREAD

**Issue by gdrdrposteo** [subgraph/subgraph-os-issues#149]
I am very sure that I'm entering the right username and password. I am just being kept asked for my password every time I press enter to try to log in after entering my credentials. Help please?

Thanks a lot!

**Comment by xSmurf** [comment]
Did you try to enter your full username as "username@dokgo.com" or just "username"?

**Comment by xSmurf** [comment]
No answer, coyim has been upgraded since and multiple users use duckgo xmpp with it. I'm closing this.
