### ISSUE TITLE
Icedove won't start

### ISSUE THREAD

**Issue by subproc** [subgraph/subgraph-os-issues#150]
icedove fails to start...log say:

Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 Launch message received. Path: /usr/bin/icedove Name:  Pwd: /home/user Args: []
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 Would launch icedove
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 Setting environment variable: GNOME_KEYRING_PID=1
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 Allowing user: video (44)
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 Allowing user: audio (29)
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Init state: &{Profile:{Name:icedove Path:/usr/bin/icedove Paths:[] ProfilePath: DefaultParams:[] AutoShutdown:yes Watchdog:[] Wrapper: Multi:false NoSysProc:false NoDefaults:false AllowFiles:false AllowedGroups:[] Whitelist:[{Path:/run/resolvconf Target: ReadOnly:false CanCreate:false Ignore:false Force:false NoFollow:false} {Path:/run/user/${UID}/keyring Target: ReadOnly:false CanCreate:false Ignore:true Force:false NoFollow:false} {Path:/tmp/gpg-* Target: ReadOnly:false CanCreate:false Ignore:true Force:false NoFollow:false} {Path:${HOME}/.cache/icedove Target: ReadOnly:false CanCreate:true Ignore:false Force:false NoFollow:false} {Path:${HOME}/.gnupg Target: ReadOnly:false CanCreate:false Ignore:true Force:false NoFollow:false} {Path:${HOME}/.thunderbird Target: ReadOnly:false CanCreate:false Ignore:true Force:false NoFollow:false} {Path:${HOME}/.icedove Target: ReadOnly:false CanCreate:true Ignore:false Force:false NoFollow:false} {Path:${XDG_DOWNLOAD_DIR}/Icedove Target: ReadOnly:false CanCreate:true Ignore:false Force:false NoFollow:false} {Path:/var/lib/oz/cells.d/icedove-whitelist.seccomp Target: ReadOnly:true CanCreate:false Ignore:false Force:false NoFollow:false} {Path:/var/lib/oz/cells.d/icedove.json Target: ReadOnly:true CanCreate:false Ignore:false Force:false NoFollow:false}] Blacklist:[] XServer:{Enabled:true TrayIcon:/usr/share/icons/hicolor/scalable/apps/icedove.svg WindowIcon: EnableTray:false EnableNotifications:false DisableClipboard:false AudioMode:none PulseAudio:false Border:false} Environment:[{Name:GPG_AGENT_INFO Value:} {Name:GNOME_KEYRING_CONTROL Value:} {Name:GNOME_KEYRING_PID Value:1}] Networking:{Nettype:empty Sockets:[{Nettype:client Proto:tcp Port:9050 Destination:}] IpByte:0 DNSMode:} Seccomp:{Mode:whitelist Enforce:true Debug:false Train:false TrainOutput: Whitelist:/var/lib/oz/cells.d/icedove-whitelist.seccomp Blacklist:}} Config:{ProfileDir:/var/lib/oz/cells.d ShellPath:/bin/bash PrefixPath:/usr EtcPrefix:/etc/oz SandboxPath:/srv/oz BridgeMACAddr:
Jun  2 14:06:19 subgraph oz-daemon[869]: XX:XX:XX:XX:XX:XX DivertSuffix: DivertPath:true NMIgnoreFile:/etc/NetworkManager/conf.d/oz.conf UseFullDev:false AllowRootShell:false LogXpra:true EnvironmentVars:[USER USERNAME LOGNAME LANG LANGUAGE _ TZ=UTC XDG_SESSION_TYPE XDG_RUNTIME_DIR XDG_DATA_DIRS XDG_SEAT XDG_SESSION_TYPE XDG_SESSION_ID] DefaultGroups:[audio video]} Sockaddr:/srv/oz/sockets/oz-init-control-ee79cf9b739755e4 LaunchEnv:[USER=user USERNAME=user LOGNAME=user LANG=it_IT.UTF-8 TZ=UTC XDG_SESSION_TYPE=x11 XDG_RUNTIME_DIR=/run/user/1000 XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share/:/usr/share/ XDG_SEAT=seat0 XDG_SESSION_TYPE=x11 XDG_SESSION_ID=3 GNOME_KEYRING_PID=1] Uid:1000 Gid:1000 Gids:map[audio:29 video:44] User:{Uid:1000 Gid:1000 Username:user Name:User HomeDir:/home/user} Network:{Interface:<nil> VethHost: VethGuest: Ip: Gateway:<nil> Class: Nettype:empty Veth:<nil> IpByte:0} Display:0}
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 oz-init (icedove) is waiting for init
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Recieved SIGUSR1 from parent (user defined signal 1), ready to init.
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Starting oz-init for profile: icedove
Jun  2 14:06:19 subgraph icedove.desktop[4392]: ok received
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind mounting (as readonly) /bin -> /srv/oz/rootfs/bin
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind mounting (as readonly) /lib -> /srv/oz/rootfs/lib
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind mounting (as readonly) /lib64 -> /srv/oz/rootfs/lib64
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind mounting (as readonly) /usr -> /srv/oz/rootfs/usr
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind mounting (as readonly) /etc -> /srv/oz/rootfs/etc
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Blacklisted path: /oz.ro.dir -> /usr/lib/gvfs
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Blacklisted path: /oz.ro.dir -> /usr/sbin
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Blacklisted path: /oz.ro.dir -> /sbin
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Blacklisted path: /oz.ro.file -> /etc/machine-id
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Blacklisted path: /oz.ro.file -> /etc/shadow
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Blacklisted path: /oz.ro.file -> /etc/shadow-
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Blacklisted path: /oz.ro.file -> /usr/bin/sudo
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Blacklisted path: /oz.ro.file -> /bin/su
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Blacklisted path: /oz.ro.file -> /bin/mount
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Blacklisted path: /oz.ro.file -> /bin/umount
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Blacklisted path: /oz.ro.file -> /bin/fusermount
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Target (/run/resolvconf > /srv/oz/rootfs/run/resolvconf) already exists, ignoring: <nil> &{resolvconf 40 2147484141 {63600473179 746697593 0xce5860} {48 618203 2 16877 0 0 0 0 40 4096 0 {1464876379 746697593} {1464876379 746697593} {1464876379 746697593} [0 0 0]}}
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind mounting  /run/user/1000/keyring -> /srv/oz/rootfs/run/user/1000/keyring
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind mounting  /home/user/.cache/icedove -> /srv/oz/rootfs/home/user/.cache/icedove
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind mounting  /home/user/.gnupg -> /srv/oz/rootfs/home/user/.gnupg
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind target (/home/user/.thunderbird) missing and ignored!
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind mounting  /home/user/.icedove -> /srv/oz/rootfs/home/user/.icedove
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind mounting  /home/user/Scaricati/Icedove -> /srv/oz/rootfs/home/user/Scaricati/Icedove
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind mounting (as readonly) /var/lib/oz/cells.d/icedove-whitelist.seccomp -> /srv/oz/rootfs/var/lib/oz/cells.d/icedove-whitelist.seccomp
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind mounting (as readonly) /var/lib/oz/cells.d/icedove.json -> /srv/oz/rootfs/var/lib/oz/cells.d/icedove.json
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] bind mounting  /home/user/.Xoz/icedove -> /srv/oz/rootfs/home/user/.Xoz/icedove
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] chroot to /srv/oz/rootfs
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Mounting /dev/pts [devpts]
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Mounting /proc [proc]
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Mounting /sys [sysfs]

Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Hostname set to (icedove.local)
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] dbus-uuid: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] xpra work dir is /home/user/.Xoz/icedove
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] Starting xpra server
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) I /usr/bin/xpra [/usr/bin/xpra --no-daemon --mmap --no-sharing --bell --system-tray --xsettings --cursors --encoding=rgb --clipboard --no-microphone --no-speaker --no-notifications --no-mdns --input-method=keep --bind=/home/user/.Xoz/icedove --socket-dir=/home/user/.Xoz/icedove start :0]
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) Warning: invalid option: 'scaling'
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) Warning: invalid option: 'html'
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) WARNING: low display number: 0
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) You are attempting to run the xpra server against what seems to be a default X11 display ':0'.
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) This is generally not what you want.
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) You should probably use a higher display number just to avoid any confusion (and also this warning message).
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) X.Org X Server 1.18.3
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) Release Date: 2016-04-04
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) X Protocol Version 11, Revision 0
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) Current Operating System: Linux icedove 4.5.5-grsec-amd64 #2 SMP Tue May 31 19:25:39 UTC 2016 x86_64
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) Kernel command line: BOOT_IMAGE=/vmlinuz-4.5.5-grsec-amd64 root=/dev/mapper/subgraph--vg-root ro initrd=/install/initrd.gz quiet splash apparmor=1 security=apparmor
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) Build Date: 05 April 2016  07:00:43AM
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) xorg-server 2:1.18.3-1 (http://www.debian.org/support)
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) Current version of pixman: 0.33.6
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) #011Before reporting problems, check http://wiki.x.org
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) #011to make sure that you have the latest version.
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) Markers: (--) probed, (**) from config file, (==) default setting,
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) #011(++) from command line, (!!) notice, (II) informational,
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) #011(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) (++) Log file: "/home/user/.xpra/Xorg.:0.log", Time: Thu Jun  2 14:06:19 2016
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) (++) Using config file: "/etc/xpra/xorg.conf"
Jun  2 14:06:19 subgraph oz-daemon[869]: 2016/06/02 14:06:19 [icedove] (xpra-server) (==) Using system config directory "/usr/share/X11/xorg.conf.d"
Jun  2 14:06:20 subgraph oz-daemon[869]: 2016/06/02 14:06:20 [icedove] (xpra-server) 2016-06-02 14:06:20,158 created unix domain socket: /home/user/.xpra/icedove-0
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,163 created unix domain socket: /home/user/.Xoz/icedove/icedove-0
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] Child process pid=38 exited from init with status 0
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,343 Warning: all the compressors are disabled,
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,344  unless you have a gigabit connection or better, performance will suffer
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,431 Failed to launch ldconfig -p: [Errno 2] No such file or directory
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,662 Error: webcam forwarding disabled:
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,662  No module named PIL
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,664 Warning: webcam forwarding is disabled
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,664  the virtual video directory '/sys/devices/virtual/video4linux' was not found
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,664  make sure that the 'v4l2loopback' kernel module is installed and loaded
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,664 found 0 virtual video devices
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,670 xpra X11 version 0.17.2-r12591
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,670  running with pid 10 on Linux debian stretch/sid
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,670  on display :0
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,761 xpra is ready.

Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] XPRA started
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 oz-init (icedove) is ready
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 Starting socket client forwarding: tcp://127.0.0.1:9050.
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] Run program message received: &{Args:[] Pwd:/home/user Path:/usr/bin/icedove}
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] Enabling seccomp whitelist for: /usr/bin-oz/icedove
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-client-stderr) I /usr/bin/xpra [/usr/bin/xpra --no-daemon --mmap --no-sharing --bell --system-tray --xsettings --cursors --encoding=rgb --clipboard --no-microphone --no-speaker --no-notifications --title=@title@ --compress=0 --no-keyboard-sync --no-tray --socket-dir=/home/user/.Xoz/icedove attach :0]
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] Child process pid=59 exited from init with status -1
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] Shutting down sandbox after child exit.
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-client-stderr) Warning: invalid option: 'scaling'
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-client-stderr) Warning: invalid option: 'html'
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,922 New unix-domain connection received on /home/user/.Xoz/icedove/icedove-0
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,922 New unix-domain connection received on /home/user/.xpra/icedove-0
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,925 Connection lost
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] (xpra-server) 2016-06-02 14:06:24,925 Connection lost
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] Error running xpra stop: exit status 1
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 [icedove] oz-init exiting...
Jun  2 14:06:24 subgraph oz-daemon[869]: 2016/06/02 14:06:24 Child process pid=4401 exited from daemon with status 0
Jun  2 14:06:25 subgraph oz-daemon[869]: 2016/06/02 14:06:25 [icedove] (xpra-client-stderr) 2016-06-02 14:06:25,099 Warning: all the compressors are disabled,
Jun  2 14:06:25 subgraph oz-daemon[869]: 2016/06/02 14:06:25 [icedove] (xpra-client-stderr) 2016-06-02 14:06:25,099  unless you have a gigabit connection or better, performance will suffer
Jun  2 14:06:25 subgraph oz-daemon[869]: 2016/06/02 14:06:25 [icedove] (xpra-client-stderr) 2016-06-02 14:06:25,099 Xpra gtk2 client version 0.17.2-r12591
Jun  2 14:06:25 subgraph oz-daemon[869]: 2016/06/02 14:06:25 [icedove] (xpra-client-stderr) 2016-06-02 14:06:25,099  running on Linux debian stretch/sid
Jun  2 14:06:25 subgraph oz-daemon[869]: 2016/06/02 14:06:25 [icedove] (xpra-client-stderr) 2016-06-02 14:06:25,100 Warning: failed to import opencv:
Jun  2 14:06:25 subgraph oz-daemon[869]: 2016/06/02 14:06:25 [icedove] (xpra-client-stderr) 2016-06-02 14:06:25,100  No module named cv2
Jun  2 14:06:25 subgraph oz-daemon[869]: 2016/06/02 14:06:25 [icedove] (xpra-client-stderr) 2016-06-02 14:06:25,100  webcam forwarding is disabled
Jun  2 14:06:25 subgraph oz-daemon[869]: 2016/06/02 14:06:25 [icedove] (xpra-client-stderr) 2016-06-02 14:06:25,141 OpenGL support is missing:
Jun  2 14:06:25 subgraph oz-daemon[869]: 2016/06/02 14:06:25 [icedove] (xpra-client-stderr) 2016-06-02 14:06:25,141  cannot import name gdkgl
Jun  2 14:06:25 subgraph oz-daemon[869]: 2016/06/02 14:06:25 [icedove] (xpra-client-stdout) xpra initialization error:
Jun  2 14:06:25 subgraph oz-daemon[869]: 2016/06/02 14:06:25 [icedove] (xpra-client-stdout)  cannot find any live servers to connect to
Jun  2 14:06:25 subgraph oz-daemon[869]: 2016/06/02 14:06:25 Child process pid=4465 exited from daemon with status 1
Jun  2 14:06:25 subgraph oz-daemon[869]: 2016/06/02 14:06:25 No sandbox found with oz-init pid = 4465

**Comment by gdrdrposteo** [comment]
Same here!

**Comment by gdrdrposteo** [comment]
Hey do you mind chatting over XMPP?

**Comment by neuralpancake** [comment]
Same here; also, both CoyIM and HexChat fail to start.

**Comment by gdrdrposteo** [comment]
Mhmmmm.

**Comment by dma** [comment]
Hi, did this get fixed? Have you updated your packages? There have been a few issues in the past couple of weeks that may have caused this. Please let me know.

**Comment by subproc** [comment]
with another dist-upgrade it's all working now, no more problem with icedove....keep up the good job...
