### ISSUE TITLE
Does Subgraph OS do something to hide it's Tor traffic by default?

### ISSUE THREAD

**Issue by gdrdrposteo** [subgraph/subgraph-os-issues#151]

**Comment by gdrdrposteo** [comment]
AFAIK Tor traffic by default isn't obfuscated.

**Comment by JasperWeiss** [comment]
No, by default SubgraphOS connects directly to the Tor network.

**Comment by gdrdrposteo** [comment]
Ah ok. Thanks!

**Comment by david415** [comment]
@gdrdrposteo hiding tor traffic by default is simply wasteful of Tor bridge bandwidth to utilize them if it isn't actually required by the user's threat model.

**Comment by gdrdrposteo** [comment]
Gotcha! Thanks!
