### ISSUE TITLE
MSI issue

### ISSUE THREAD

**Issue by msisucks** [subgraph/subgraph-os-issues#154]
"ACPI : EC: Fail in evaluating the _REG object of EC device. Broken bios is suspected."

I get that error message when booting up just stays like that. Its not just subgraph but every linux distro i tired. I am wondering if you can provide a patch or something I found this related bug here https://bugzilla.kernel.org/show_bug.cgi?id=112261

let me know if this is an issue you get fixed, thanks.

**Comment by xSmurf** [comment]
Unless it gets fixed upstream I don't see this as something we will fix. Sorry.
