### ISSUE TITLE
browser

### ISSUE THREAD

**Issue by paymonyaminisharif** [subgraph/subgraph-os-issues#158]
default browser (not talking tor browser here) should be chromium. openbsd has pledge for chromium, the codebase has been under much scrutiny since it was practically written by the nsa, and mozilla is shit software with shit management, so iceweasel is just a refusal to let firefox die. oppositional defiance is usually a good thing in the security world but not in this case. let it go kids... let it go. everyone is writing all the next gen webrtc/websocket stuff for chromium anyway (xmpp, torrent, bitcoin, everything). im pretty sure the industry will move to a chromium based tor-browser replacement as well.  i wouldnt feel so strongly about this if openbsd didnt pledge chromium. but now the entire openbsd userbase will be watching that code behave. its like an indirect security audit and oz needs to participate. :)

**Comment by dma** [comment]
For TorBrowser we're stuck with Firefox. Chromium works well in SGOS, and we are using it ourselves now. Will be more important as we add "beyond Tor" flexibility to Subgraph OS.

**Comment by Gridlocked** [comment]
'Beyond Tor' flexibility is great news.  

Oz and a default Grsec kernel will be a huge draw for people looking for a secure OS.
