### ISSUE TITLE
Tor Browser don't start

### ISSUE THREAD

**Issue by SpiderParker** [subgraph/subgraph-os-issues#159]
I have installed Subgraph OS today. I tried many times to start Tor but it don't work. I've used some commands in the terminal but it don't work too. Sorry for this question but i'm a newbie :/

**Comment by dma** [comment]
Hi, can you try this command:

sudo /sbin/paxrat -f /etc/paxrat/paxrat_tbl.conf

An then try again?

Some other basic troubleshooting questions:

Did the Tor Browser Launcher download successfully complete? Are you connected to Tor? Do you have network access? Is your system time correct?

**Comment by SpiderParker** [comment]
![tmp_5872-img_20160628_212007753300901](https://cloud.githubusercontent.com/assets/15092820/16429625/117b1b10-3d78-11e6-8b9e-4df591d5fe89.jpg)
![tmp_5872-img_20160628_212053-181595638](https://cloud.githubusercontent.com/assets/15092820/16429629/1855892a-3d78-11e6-9fd8-8d28e8a4d67a.jpg)
![tmp_5872-img_20160628_212725-1953527240](https://cloud.githubusercontent.com/assets/15092820/16429721/92197adc-3d78-11e6-8c04-0368d9afc7b5.jpg)


 I try this command line but I don't know what I need to do after. Tor's download was successfully complete, I'm connecter to Tor (I had a notification) and I'm connecter to my Box by Wi-Fi. The system's tome is correct.

**Comment by dma** [comment]
Sorry. I'm giving you bad instructions. The command flag is -c. Run: /sbin/paxrat -c /etc/paxrat/paxrat_tbl.conf. I always make this mistake :)

**Comment by SpiderParker** [comment]
I'm not sure to have good written command line.
![tmp_549-img_20160628_215530753300901](https://cloud.githubusercontent.com/assets/15092820/16430260/0fca96da-3d7b-11e6-9a75-8f9c9d4aefe3.jpg)

**Comment by dma** [comment]
sudo /sbin/paxrat -c /etc/paxrat/paxrat_tbl.conf

**Comment by SpiderParker** [comment]
![2016-06-28 22 05 03](https://cloud.githubusercontent.com/assets/15092820/16430554/76fb9646-3d7c-11e6-8f4d-75af61a7fef2.jpg)

I got this message.

**Comment by dma** [comment]
there needs to be a space after the -c. Exactly like this:

sudo /sbin/paxrat -c /etc/paxrat/paxrat_tbl.conf

**Comment by SpiderParker** [comment]
![2016-06-28 22 10 52](https://cloud.githubusercontent.com/assets/15092820/16430707/37d561b2-3d7d-11e6-8b70-9ba04412d733.jpg)

OK.

**Comment by dma** [comment]
Did Tor Browser work after you did that?

**Comment by SpiderParker** [comment]
No, Tor don't start :/

**Comment by SpiderParker** [comment]
Problem solved ! Thank you for your help, I've reinstall Subgraph. It works :)
