### ISSUE TITLE
High-DPI quirks

### ISSUE THREAD

**Issue by willscott** [subgraph/subgraph-os-issues#162]
The resolution of the desktop is not consistent in a High-DPI environment.

On the app screen, the mouse becomes very small.
Tor Browser, and most other oz-run apps are displayed too small.
when run directly from the sandbox ("Open terminal in sandbox" and then executing the binary) they render at the correct resolution.

**Comment by xSmurf** [comment]
I think I know what this is about, I'll investigate a bit more!

**Comment by xSmurf** [comment]
Hey @willscott, would you mind replacing your `/etc/xpra/xpra.oz.conf` with https://github.com/subgraph/oz/blob/master/sources/etc/xpra/xpra.oz.conf and seeing if this helps? (You'll want to restart oz-daemon and sandboxes)

**Comment by willscott** [comment]
👍 I haven't noticed problems yet since updating to this version.

**Comment by xSmurf** [comment]
Fantastic! This is in the package (>=0.1.0) as well!

Thanks for the feedback :100:, sorry it took so long to close :/
