### ISSUE TITLE
"sudo apt upgrade" causes sandboxing system to fail

### ISSUE THREAD

**Issue by Hapon123** [subgraph/subgraph-os-issues#165]
Something in the "upgrade" causes Oz/Sandbox not to function properly. I have re-installed the OS a number of times and with different iso downloads to draw this conclusion. The sandbox works fine with the initial install and the sudo apt update but the sudo apt upgrade causes sandbox system failure. LibreOffice will not open, and Tor opens but with one right-click to open a link the sandbox freezes.  Non-sandbox systems seem fine.  I am very excited about this system! Thank you for your work!

**Comment by dma** [comment]
Hey, this is a known issue, we are about to deploy an updated Oz package to fix it. If you want an immediate fix, clone the github.com/subgraph/oz repo and copy oz/profiles/*.seccomp into /var/lib/oz/cells.d/.

**Comment by dma** [comment]
I'll keep it open until the package is actually in the repo.

**Comment by Hapon123** [comment]
Okay, thank you!

**Comment by dma** [comment]
Upgraded oz package (0.0.23) in repo. Please upgrade and let us know if there are any further problems.
