### ISSUE TITLE
After First Install Login loop - Cant login

### ISSUE THREAD

**Issue by david-maus** [subgraph/subgraph-os-issues#168]
Hi,

i have seen a similar issue here:
https://github.com/subgraph/subgraph-os-issues/issues/146

The difference is that i cant login after the first install. So, there is nothing configured (Wifi etc..)

**Comment by xSmurf** [comment]
Assuming this to be fixed upstream. If this is not the case, please re-open including details on your graphics card (make and model), the output of `dmesg`, and `/var/log/syslog`.
