### ISSUE TITLE
Audio currently broken in OZ sandboxes.

### ISSUE THREAD

**Issue by subproc** [subgraph/subgraph-os-issues#170]
there's no audio with vlc
syslog say:
[vlc](xpra-client-stderr) 2016-07-30 21:53:40,825 Attached to :0 (press Control-C to detach)
Jul 30 21:53:40 subgraph oz-daemon[2288]: 2016/07/30 21:53:40 [vlc](xpra-client-stderr)
Jul 30 21:53:40 subgraph oz-daemon[2288]: 2016/07/30 21:53:40 [vlc](xpra-server) 2016-07-30 21:53:40,840 python netifaces package is missing
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](stderr) shm_open() failed: No such file or directory
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](stderr) ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Protocol error
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](stderr)
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](stderr) [000000000133fc08] alsa audio output error: cannot open ALSA device "default": Connection refused
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](stderr) [000000000133fc08] core audio output error: module not functional
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](stderr) [0000033bf0c064c8] core decoder error: failed to create audio output
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server) 2016-07-30 21:53:41,391 Error during encoding:
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server) Traceback (most recent call last):
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server)   File "/usr/lib/python2.7/dist-packages/xpra/server/source.py", line 2099, in encode_loop
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server)     fn_and_args[0](*fn_and_args[1:])
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server)   File "/usr/lib/python2.7/dist-packages/xpra/server/window/window_source.py", line 561, in compress_and_send_window_icon
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server)     assert wrapper.datatype in ("premult_argb32", "png")
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server) AssertionError
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server) 2016-07-30 21:53:41,407 Error during encoding:
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server) Traceback (most recent call last):
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server)   File "/usr/lib/python2.7/dist-packages/xpra/server/source.py", line 2099, in encode_loop
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server)     fn_and_args[0](*fn_and_args[1:])
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server)   File "/usr/lib/python2.7/dist-packages/xpra/server/window/window_source.py", line 561, in compress_and_send_window_icon
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server)     assert wrapper.datatype in ("premult_argb32", "png")
Jul 30 21:53:41 subgraph oz-daemon[2288]: 2016/07/30 21:53:41 [vlc](xpra-server) AssertionError

**Comment by conorsch** [comment]
I am able to run oz-sandboxed vlc with audio, so I believe this issue has already been fixed. Consider closing, @xSmurf.

**Comment by dma** [comment]
Yes, fixed a while ago and is not an issue in the Dec 2016 ISO.
