### ISSUE TITLE
Install does not work

### ISSUE THREAD

**Issue by aanastos** [subgraph/subgraph-os-issues#172]
Tried making usb flash with iso but installer does not load instead just blinking white cursor
and prompt about cdrom. Seems the iso has some issues but now I go to re-download and the download link is 404 errors https://subgraph.com/download/index.en.html

**Comment by xSmurf** [comment]
How did you make the usb key? If you used dd, make sure you run and complete the `sync` command after dd completes; this is the most common cause of the blinking cursor.

I'm not sure where you got this link, the proper link is, and has always been, https://subgraph.com/sgos/download/index.en.html

**Comment by xSmurf** [comment]
I'll close this for now, if there is more information and it isn't the above stated issue, feel free to reopen.
