### ISSUE TITLE
i can not verify subgraph ISO

### ISSUE THREAD

**Issue by sissisi** [subgraph/subgraph-os-issues#173]
Good morning,

there is a problem about subgraph.

My OS is debian jessie, and i can not import your public key.
I can not import your public key (BAD uri, key server no found).
Beside, with your explainations, there is not fingerprint.

Can you add public gpg in your website, here: https://subgraph.com/sgos/download/index.en.html
and show fingerprint of public key, please.

I think that it is so important, because many people can not verify subgraph's ISO, to verify integrity.

Therefore, with tor, there is a warning with download, the certificate is wrong, (bad domain)

Thanks.

**Comment by arowley0** [comment]
Here is one way to do it.

`apt-get install irssi`

or another irc client 

`irssi`

Run irssi or your irc client of choice

`/connect OFTC`

If you're using irssi, paste or type that into irssi
along with the following command

`/join #subgraph`


Look at the topic above the roster. 
You will likely find what you are looking for there.

**Comment by xSmurf** [comment]
I'm not sure I understand, the fingerprint is already on that page,

```
Secondly verify the signature of the shasum file:

gpg --recv-key B55E70A95AC79474504C30D0DA11364B4760E444
```

The public key is available on various keyservers such as `pgp.mit.edu` and `keys.gnupg.net`.

**Comment by arowley0** [comment]
My apologies. 
I misread your post @sissisi.

I'd like to hitch on to what xSmurf mentioned about the various keyservers you can use.
I was having difficulty verifying the signature of the shasum file without specifying a keyserver.
Adding the --keyserver option worked for me.
Have you tried specifying which keyserver like this? 

`gpg --recv-key --keyserver keys.gnupg.net B55E70A95AC79474504C30D0DA11364B4760E444`

if that step goes as expected you should see something similar to this below the aforementioned command.

`gpg: requesting key 4760E444 from hkp server keys.gnupg.net`
`gpg: key 4760E444: "Subgraph Release Signing Key <release@subgraph.com>" not changed`
`gpg: Total number processed: 1`
`gpg:              unchanged: 1`

After that I believe you can continue onto the next step which is to
verify the shasum. Make sure to verify the shasum file and not the iso!

I hope this helps. :penguin: :sparkles: :

**Comment by sissisi** [comment]
Hi,

@arowley0 @xSmurf:

with keyserver keys.gnupg.net, it works very well.

Thanks for your help, it is useful!

**Comment by gotlen** [comment]
I'm having the same problem today: the instructions on https://subgraph.com/sgos/download/index.en.html

```
gpg --recv-key B55E70A95AC79474504C30D0DA11364B4760E444
# You can also get the fingerprint in the title of our IRC channel!
gpg --verify subgraph-os-alpha_2016-12-30_1.iso.sha256.sig subgraph-os-alpha_2016-12-30_1.iso.sha256
```
First of all, I cannot find the key with ID B55E70A95AC79474504C30D0DA11364B4760E444 on any keyserver (tried MIT, SKS-pool).

Second, when I try to verify the signature on the SHA256-sum, it turns out it has been signed with a different key: AB6C7E344F633E104377D595E1AE39C4F999D968

```
% gpg --verify subgraph-os-alpha_2016-12-30_1.iso.sha256.sig subgraph-os-alpha_2016-12-30_1.iso.sha256
gpg: Signature made Fri 30 Dec 2016 10:16:21 PM CET
gpg:                using RSA key AB6C7E344F633E104377D595E1AE39C4F999D968
gpg: Can't check signature: No public key
```
This other key is also not available on any keyservers.
