### ISSUE TITLE
Add chromium flags to paxrat config.

### ISSUE THREAD

**Issue by xSmurf** [subgraph/subgraph-os-issues#175]
Would be useful if we could add the chromium flags to the paxrat config.

```
  "/usr/lib/chromium/chromium": {
    "flags": "m"
  },
```

**Comment by rsdy** [comment]
Calling `paxrat -b /usr/lib/chromium/chromium -s m` was enough to get a functional chromium for me.

**Comment by xSmurf** [comment]
Merged upstream, it will appear in the next release!
