### ISSUE TITLE
Updates have hung when "/usr/lib/apt/methods/http wants to connect"

### ISSUE THREAD

**Issue by jlj2** [subgraph/subgraph-os-issues#177]
During updates, system has been hanging with a black Gnome message such as "/usr/lib/apt/methods/http wants to connect to mirrorservice.org on TCP Port 80."  This has happened during different sessions at any one of the three of the updating stages:

```
    sudo apt update
    sudo apt upgrade
    sudo apt dist-upgrade --auto-remove --purge
```

The system hadn't been able to go fully through all of those update stages successfully during any session because of this issue up until today. 

Different urls have been queried in this way during updates besides the url reported above.  "Firewall Settings" recorded that connections for various other urls have been accepted using the same path as above (/usr/lib/apt/methods/http) through port 80, but not the url queried above, for example. 

The mouse pointer could move during the hang but would not record a click to "Accept" or "Deny" the connection.

The only options used were forced shutdowns.

However, the solution tried today for issue #176 (re Tor being disabled at install) i.e. `sudo apt-get install roflcoptor` plus a reboot somehow may also have had a bearing to resolve this current issue re update hangs:  immediately after installing roflcoptor (and ?dependency procsnitchd) plus rebooting, a full update including upgrade and purge were successful on first attempt (no hangs, and clicks accepted any suggested connection).  (Could there be a causal relation?)

**Comment by xSmurf** [comment]
No other reports, multiple fixes since, new release image. I will close this sadly. Feel free to re-open if you experience this one the new release.
