### ISSUE TITLE
Network constantly in 'connecting' state according to gnome

### ISSUE THREAD

**Issue by whatisgravity** [subgraph/subgraph-os-issues#181]
This card works in Tails, Debian, etc. The card is a Qualcomm Atheros Killer E220x

Gnome reports an indefinite connecting state. 

/var/log/syslog reports constant searching for DHCP discovery, eventually times out. (reason 'ip-config-unavailable')

**aside** The mac address switches between two values. systemctl networking fails when starting in the process of configuring the interfaces. 

I suspect it is a problem with Oz failing to start initiate the bridge connection. I will document what I do to fix this. 
---

I searched and did not find this so I felt I should open the issue and document the fix in case others run into this problem. If you do have  a solution that would be wonderful too.

**Comment by xSmurf** [comment]
Almost certainly has nothing to do with OZ. Could you provide a dump of `lspci -nn -vv`, `dmesg`, and `lsmod`?

**Comment by xSmurf** [comment]
No return, closing. Feel free to re-open.
