### ISSUE TITLE
to be useful to most people around the world the tor control needs to be more advanced

### ISSUE THREAD

**Issue by cptfoo** [subgraph/subgraph-os-issues#182]
Not everyone lives in the US, and we can not just connect to Tor. We need to be able to connect to Tor through a VPN. 

One should be able to LAN too, without being able to connect to LAN there is no advantage to using subgraph over Tails. Tais already fundamentally offers everything this offers but Tails does it better.

If you want this to be an OS that average users can use, we need to be able to connect through VPN, LAN, VPN+Tor and just Tor. Right now it is useless to almost everyone but it does not need to be that way, fix this early on - dont put this off till the future.

**Comment by xSmurf** [comment]
You can already connect to the LAN.

There are multiple tickets for flexible routing already I'm closing this as a duplicate.
