### ISSUE TITLE
firewall gnome extension doesn't work

### ISSUE THREAD

**Issue by beauraF** [subgraph/subgraph-os-issues#185]
Hi,

Gnome firewall extension is actually broken.

![capture d ecran de 2016-09-17 01-52-27](https://cloud.githubusercontent.com/assets/12185788/18604179/ebbf0424-7c68-11e6-9f66-8ae8a7d933a5.png)
![extension](https://cloud.githubusercontent.com/assets/12185788/18604180/ebcf3182-7c68-11e6-9472-54674b9c931a.png)

**Comment by xSmurf** [comment]
Could you provide `apt-cache policy gnome-shell fw-daemon-gnome` ? There was a small period of time between a gnome-shell upgrade and fw-daemon upgrade during which  the fw-daemon extension (not the daemon) may have stopped working. Make sure your fw-daemon-gnome is up to date with version `0.0.4`.

**Comment by beauraF** [comment]
Hi xSmurf,

Sorry for the late reply ... I updated my `fw-daemon-gnome` and everything is back in order.

Thank you.

**Comment by xSmurf** [comment]
Fantastic, sorry for the mess up, there's a gnome transition going on right now and it's been a bit bumpy.


Permis Vacances Travail, I guess not ;)

**Comment by beauraF** [comment]
No problem. I should have done the updates before opening an issue.
That is what I thought. But nop, studies in Quebec for a year.

Thank you for your help. Have a nice day. :)
