### ISSUE TITLE
systemd worries

### ISSUE THREAD

**Issue by burdges** [subgraph/subgraph-os-issues#187]
Just noticed [this pretty damning indictment of `systemd`'s security practices](https://www.agwa.name/blog/post/how_to_crash_systemd_in_one_tweet).  I suppose you guys already rank `systemd` as dangerous, but maybe worth reiterating.

**Comment by xSmurf** [comment]
I don't think we will be fighting this battle at the host level for now.

It's worth nothing though systemd doesn't run at the OZ sandbox level, and neither are its associated sockets available to sandboxes.

**Comment by hasufell** [comment]
> I don't think we will be fighting this battle at the host level for now.

There is no fight involved. Systemd isn't mandatory at all. It's just a distro-level decision. If you choose a distro that doesn't give choice to the user, ofc you'll be locked on systemd.

**Comment by mckinney-subgraph** [comment]
Closing this. We're a `systemd` based distribution. Feel free to fork us or use another non-systemd based distro if this is a deal breaker for you.

**Comment by hasufell** [comment]
> or use another non-systemd based distro

That's a perfect choice. Thanks for clarifying.
