### ISSUE TITLE
Installer looking for debian release codename.  

### ISSUE THREAD

**Issue by Frimbleglim** [subgraph/subgraph-os-issues#191]
Hi,  I thought I would try out subgraph.  

The installer refuses to work without a debian release codename which it can't find.  

This is on a brand new Lenovo pc installing to the hard drive (As opposed to a VM)

**Comment by xSmurf** [comment]
Most likely this is an issue with images produced under windows. See #144.

Closing as duplicate, if it's something different you'll need to provide more detailed logs of the error.

**Comment by Frimbleglim** [comment]
Nothing like that bug.  And the usb was made using linux mint 18 not windows.  

The issue is at the install system step of the installer process.  

Happy to provide log files ect. what do you need?
