### ISSUE TITLE
virtualbox-guest-dkms 5.1.10 not building

### ISSUE THREAD

**Issue by vitteloil** [subgraph/subgraph-os-issues#193]
Hi,
package virtualbox-guest-dkms 5.1.10 is not building.
Error in build log is : **stack protector enabled but compiler support broken**

GCC is 6.2.0
kernel is 4.7.9-grsec-amd64

**Comment by xSmurf** [comment]
This is an extremely old kernel which was, if memory serves, compiled against a different version of GCC.

That said, VirtualBox is getting pull out of the Debian repository and we will likely not offer further support for running it inside SGOS. We are putting up a guide on using Qemu/KVM and frontends such as `virt-manager`. Please see the https://github.com/subgraph/sgos_handbook for further information.
