### ISSUE TITLE
[After initial installation] Strange repos are loaded on first update/upgrade. How can this be avoided ?

### ISSUE THREAD

**Issue by Wikinaut** [subgraph/subgraph-os-issues#194]
I strictly followed the instructions on https://subgraph.com/sgos/download/index.en.html especially I mean the section 
```
After installing
After the installation process, you should upgrade the system by running the following:
[Add here: 'open a "Terminal" in "Activities > Applications" and then type']
sudo apt update
sudo apt upgrade
sudo apt dist-upgrade --auto-remove --purge
```
After installation I noticed, that I have to expressly allow (switch on) the network (here: cable LAN connection), this should be added on https://subgraph.com/sgos/download/index.en.htm page.

But more severe is this:

While running `apt update` a huge amount of accesses (about 20..30) has to be manually allowed, accesses to wikipedia.something, to something.ro and so on, which I regard as suspicious. I would like to have a preconfigured list, or at least a list here of repos which you "can" recommended to be safe for "allow access".

Pls. advice/explain.

**Comment by vitteloil** [comment]
@Wikinaut , what you are seeing is that subgraph is using many different mirrors to fetch the updates. This is normal, since you are going through Tor, it's fetching different mirrors because the tor outproxy used is not always the same, and thus, because the best mirror is selected, you are hitting different mirrors.

In the firewall, allow 'all' for 'http/get' and you'll be fine.

**Comment by Wikinaut** [comment]
@vitteloil and what if I want to deny certain countries, for example ?

**Comment by xSmurf** [comment]
@Wikinaut the debian mirrors don't allow exclusions, you can however select a specific mirror in `/etc/apt/sources.list` instead of httpredir if that pleases you. Not that there's much of a point to it, imho.

**Comment by Wikinaut** [comment]
Thanks.
