### ISSUE TITLE
Kernel 4.9

### ISSUE THREAD

**Issue by ghost** [subgraph/subgraph-os-issues#200]
Can we get Kernel 4.9? So many improvements over 4.9 and I believe it is the Kernel debian has picked?

**Comment by xSmurf** [comment]
grsecurity patches for 4.9 aren't yet released (latest is 4.8.17). FWIW We are still some ways in advanced comparatively to Debian testing (4.8.15 vs 4.8.11), and will continue tracking, roughly, the grsecurity patch testing releases.
