### ISSUE TITLE
Unable to verify Subgraph ISO; keys not available on keyservers

### ISSUE THREAD

**Issue by gotlen** [subgraph/subgraph-os-issues#201]
I've tried following the the instructions on https://subgraph.com/sgos/download/index.en.html

```
gpg --recv-key B55E70A95AC79474504C30D0DA11364B4760E444
# You can also get the fingerprint in the title of our IRC channel!
gpg --verify subgraph-os-alpha_2016-12-30_1.iso.sha256.sig subgraph-os-alpha_2016-12-30_1.iso.sha256
```
First of all, I cannot find the key with ID B55E70A95AC79474504C30D0DA11364B4760E444 on any keyserver (tried MIT, SKS-pool).

Second, when I try to verify the signature on the SHA256-sum, it turns out it has been signed with a different key: AB6C7E344F633E104377D595E1AE39C4F999D968

```
% gpg --verify subgraph-os-alpha_2016-12-30_1.iso.sha256.sig subgraph-os-alpha_2016-12-30_1.iso.sha256
gpg: Signature made Fri 30 Dec 2016 10:16:21 PM CET
gpg:                using RSA key AB6C7E344F633E104377D595E1AE39C4F999D968
gpg: Can't check signature: No public key
```
This other key is also not available on any keyservers.

**Comment by jaspermine** [comment]
This worked for me.

gpg --keyserver wwwkeys.uk.pgp.net --recv-key B55E70A95AC79474504C30D0DA11364B4760E444

**Comment by dma** [comment]
It's here:

https://sks-keyservers.net/pks/lookup?op=get&search=0xDA11364B4760E444

??

(but we will add it to our website)
