### ISSUE TITLE
share via onionshare option doesn't work

### ISSUE THREAD

**Issue by verilyisay** [subgraph/subgraph-os-issues#208]
If you download a file in the tor browser, then open the download folder, right click on the file, and select share via onionshare, the file does not get added to onionshare. 

You also can not drag and drop files from the tor browser download folder to onionshare.

This may be related. If you double click on an mp3 file in the tor browser downloads folder it will not open in VLC.

Keep up the great work.

**Comment by dma** [comment]
At least for now, files need to be opened in their own sandboxes from outside of the sandbox.

So, in the case of Onionshare, open the file explorer and find the file on the filesystem and share via right click from there.

Same idea with VLC.
