### ISSUE TITLE
Cannot install other operating system once Subgraph OS is installed

### ISSUE THREAD

**Issue by Obscurus99** [subgraph/subgraph-os-issues#212]
Hi. I recently installed the Subgraph OS on my pc but now wish to uninstall it since none of the applications were working. However, each time I tried booting another OS disk the installation would get killed. I tried Ubuntu, Xubuntu and Windows 7 with the same results. How do I permit another OS to run or install on my PC?

**Comment by xSmurf** [comment]
This doesn't appear to be a Subgraph OS issue, but a problem with your new bootloader. SubgraphOS can't take over another running operating system...
