### ISSUE TITLE
Subgraph OS doesn't boot on Heads/x230

### ISSUE THREAD

**Issue by ciaby** [subgraph/subgraph-os-issues#219]
I've been experimenting a bit with Heads (https://github.com/osresearch/heads) to have a fully trusted boot chain on my laptop. I can make QubesOS boot on it with no problems. SubgraphOS, however, can't even start in live mode. There is something wrong going on with USB which times out at boot. I can take a screenshot and submit it. Can it be related to not having a BIOS, or maybe grsec?

**Comment by xSmurf** [comment]
Screenshot might be useful yeah. I use a very similar setup to heads and it works for me. So I can't think of anything obvious.

**Comment by ciaby** [comment]
Ok, I just tried again and it crashes on the framebuffer. Do you boot directly from coreboot or do you kexec it from a running linux kernel?

**Comment by ciaby** [comment]
Digging a bit more, looks like a kexec-specific problem. I won't bother you here unless I can't fix it myself :)

**Comment by ciaby** [comment]
Ok, I found the fix :D intel_iommu=on has to be specified on the kernel command line.
