### ISSUE TITLE
Non-sandboxed applications over Tor can't use HTTPS (sometimes)

### ISSUE THREAD

**Issue by rsdy** [subgraph/subgraph-os-issues#223]
Sometimes I have problems reproducing this, but tools like `git` consistently don't work using HTTPS over Tor. I have the same issue come up with `wget`, and other unsandboxed command line tools as well. If I pull up an SSH tunnel, things magically start working.

For example:
```
user@subgraph:~/Documents/nofear$ git pull
fatal: unable to access 'https://github.com/cappsule/nofear/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
user@subgraph:~/Documents/nofear$ ssh -fNTD 10000 ssh_over_onion ; export ALL_PROXY=socks5://localhost:10000                                                                                                
user@subgraph:~/Documents/nofear$ git pull
... working git
```

In this particular case, github.com:443 is allowed on the firewall permanently, and thus I see no firewall popups at all. Using the Tor Browser, I can access any website without issues, so it's unlikely this is a malicious exit node.

**Comment by xSmurf** [comment]
Actually this sounds exactly like a malicious exit node (or just plain bad circuit). Does this problem persist after requesting a new circuit (In the system menu > Tor Network > New Identity)?

> Using the Tor Browser, I can access any website without issues

You wouldn't get the same circuit from the TBB

**Comment by rsdy** [comment]
It makes sense why TBB would work. However, after trying several new identities, I still get the same error consistently across all of them.

**Comment by xSmurf** [comment]
No more reports, considering stale. Re-open if needed.
