### ISSUE TITLE
Chromium sandbox does not inherit the host GTK theme

### ISSUE THREAD

**Issue by rsdy** [subgraph/subgraph-os-issues#224]
The colour scheme and theme settings are easily fixed by copying the `environment` block from the Evince sandbox description file, however the fonts aren't inherited, and therefore stay big and ugly.

`/var/lib/oz/cells.d/chromium.json`
```
, "environment": [
        {"name":"GTK_THEME", "value":"Adwaita:dark"}
        , {"name":"GTK2_RC_FILES", "value":"/usr/share/themes/Darklooks/gtk-2.0/gtkrc"}
]
```

**Comment by xSmurf** [comment]
Closing as duplicate, this is an existing issue specific to OZ: https://github.com/subgraph/oz/issues/27
