### ISSUE TITLE
Need fully functional inotify golang package

### ISSUE THREAD

**Issue by shw700** [subgraph/subgraph-os-issues#230]
The package we were using at one point was https://github.com/golang/exp/tree/master/inotify  ... and this was totally sufficient and functional for our needs. Unfortunately, it's been deprecated. All the currently maintained replacement packages have one severe shortcoming: none of them allow for both free form entries of inotify events to be watched and for receipt of arbitrary inotify events.

This is a result of all replacement packages angling for cross-platform compatibility. Therefore, special watch flags that might not be supported on all OS'es aren't supported. Also, in order to normalize watcher behavior, the events that are returned don't correspond directly to the Linux-specific flags. For example, an event for "file move to" might get consolidated with file creation. Similarly, other flags are grouped together into parent event categories.

golang/exp/inotify should suit our purposes just fine. We have no concerns about any non-Linux platforms. Paxrat currently depends on non-portable inotify functionality, and sublogmon would overcome one noted shortcoming if a traditional inotify-based file event monitoring package were used. This package's code seems stable and shouldn't require much maintenance.

I think we should fork it.

**Comment by mckinney-subgraph** [comment]
Closed, forked, see here:
[https://github.com/subgraph/inotify](https://github.com/subgraph/inotify)
