### ISSUE TITLE
hexchat

### ISSUE THREAD

**Issue by EmailTaken** [subgraph/subgraph-os-issues#231]
So hexchat is installed by default. Upon opening it I've added a server to the list of defined servers within hexchat. Done all the usual. But it appears all connections from hexchat are being blocked.
What should I do? Sorry in advance I'm a bit of a noob!

**Comment by EmailTaken** [comment]
Mar 23 08:45:44 subgraph oz-daemon[15686]: 2017/03/23 08:45:44 [hexchat] (xpra-server) 2017-03-23 08:45:44,283 Error during encoding:
Mar 23 08:45:44 subgraph oz-daemon[15686]: 2017/03/23 08:45:44 [hexchat] (xpra-server) Traceback (most recent call last):
Mar 23 08:45:44 subgraph oz-daemon[15686]: 2017/03/23 08:45:44 [hexchat] (xpra-server)   File "/usr/lib/python2.7/dist-packages/xpra/server/source.
Mar 23 08:45:44 subgraph oz-daemon[15686]: 2017/03/23 08:45:44 [hexchat] (xpra-server)     fn_and_args[0](*fn_and_args[1:])
Mar 23 08:45:44 subgraph oz-daemon[15686]: 2017/03/23 08:45:44 [hexchat] (xpra-server)   File "/usr/lib/python2.7/dist-packages/xpra/server/window/
Mar 23 08:45:44 subgraph oz-daemon[15686]: 2017/03/23 08:45:44 [hexchat] (xpra-server)     assert wrapper.datatype in ("premult_argb32", "png")
Mar 23 08:45:44 subgraph oz-daemon[15686]: 2017/03/23 08:45:44 [hexchat] (xpra-server) AssertionError

**Comment by EmailTaken** [comment]
^ Thats from sudo journalctl

**Comment by xSmurf** [comment]
Answered over IRC.
