### ISSUE TITLE
fix devrepo.subgraph.com to aid Subgraph OS build process understanding

### ISSUE THREAD

**Issue by adrelanos** [subgraph/subgraph-os-issues#238]
As [reported](https://secure-os.org/pipermail/desktops/2016-May/000121.html) earlier by another user, but that may have been lost...

I would like to learn more about Subgraph OS internals. They way this is usually done is looking through the apt repository to see what packages are there to get a high level overview. Subgraph OS apt repository https://devrepo.subgraph.com is showing `403 Forbidden`. That does not increase security but is a severe blocker in understanding Subgraph OS.

Please fix by allowing directory listings on https://devrepo.subgraph.com.

**Comment by mckinney-subgraph** [comment]
`https://devrepo.subgraph.com` does not contain any Subgraph OS internals (??) that I am aware of. Please clarify what you mean by Subgraph OS internals. 

I don't mind turning directory listings on. I didn't imagine it was severely blocking somebody. There are other ways to obtain the same information (use the links in the Secure Desktops message, look at `/var/lib/apt/lists` locally, run aptitude, or even take apart the ISO) in the meantime.

**Comment by xSmurf** [comment]
There are no "subgraph-os-internals"; everything is available via the [Release files](https://devrepo.subgraph.com/subgraph/dists/stretch/Release), so you should already have access to everything. Also looking at the [live build configs](https://github.com/subgraph/subgraph_desktop_stretch/tree/master/config/package-lists) will give someone plenty of insight as well.

> I don't mind turning directory listings on. - @mckinney-subgraph

I think we can close this ticket, ample answers were provided here and we've agreed to turn on dir listing eventually, for what ever that's worth.

**Comment by adrelanos** [comment]
Directory listings on https://devrepo.subgraph.com are disabled. Could you please reopen and enable directory listings?

**Comment by mckinney-subgraph** [comment]
They are enabled, you just have to go here:
https://devrepo.subgraph.com/subgraph/

**Comment by adrelanos** [comment]
Great!
