### ISSUE TITLE
Travis CI integration for Debian package build status

### ISSUE THREAD

**Issue by mckinney-subgraph** [subgraph/subgraph-os-issues#242]
Add `Travis CI` configs to our Debian packages so that we can track and display their build statuses. Build status should be shown in the README files for each individual package.

**Comment by kibal** [comment]
I have enabled a fork of travis.debian.net for all our Debian packages: https://travis-ci.org/subgraph

**Comment by kibal** [comment]
The following packages build and are also considered build failures due to lintian:

https://travis-ci.org/subgraph/subgraph-apt-config
```
E: subgraph-apt-config: package-installs-apt-preferences etc/apt/preferences.d/linux-image.pref
E: subgraph-apt-config: package-installs-apt-preferences etc/apt/preferences.d/xpra.pref
```

https://travis-ci.org/subgraph/oz
```
E: oz-daemon: description-starts-with-package-name
E: oz-daemon: diversion-for-unknown-file etc/xpra/xpra.conf preinst:21
```

https://travis-ci.org/subgraph/gnome-shell-extension-torstatus
```
E: gnome-shell-extension-torstatus: copyright-file-contains-full-gpl-license
E: gnome-shell-extension-torstatus: copyright-should-refer-to-common-license-file-for-gpl
```

https://travis-ci.org/subgraph/gnome-shell-extension-ozshell
```
E: gnome-shell-extension-ozshell: copyright-file-contains-full-gpl-license
E: gnome-shell-extension-ozshell: copyright-should-refer-to-common-license-file-for-gpl
```

https://travis-ci.org/subgraph/gnome-session-subgraph
```
E: gnome-session-subgraph: diversion-for-unknown-file usr/share/xsessions/gnome-classic.desktop preinst:11
E: gnome-session-subgraph: diversion-for-unknown-file usr/share/wayland-sessions/gnome-wayland.desktop preinst:14
```

**Comment by kibal** [comment]
ozshell and torstatus were simple fixes. The others need to be fixed by their respective packagers.
