### ISSUE TITLE
Play a song in VLC from a TrueCrypt volume

### ISSUE THREAD

**Issue by ProtenSLO** [subgraph/subgraph-os-issues#245]
I'm triing to play a file from a TrueCrypt mounted Volume but it doesn't open. What exactly can I do?

**Comment by xSmurf** [comment]
Where is the volume mounted? Only files from $HOME and `/media/user` are allowed to be binded inside the sandbox.

**Comment by xSmurf** [comment]
No return from OP, closing. Feel free to re-open if needed.
