### ISSUE TITLE
Wifi says connected, but no internet

### ISSUE THREAD

**Issue by xmbwd** [subgraph/subgraph-os-issues#246]
On a new install of `subgraph`, my wifi appears to be working and says it is connected to a wireless AP connected to the internet.  However, no actual network traffic is passing through -- Tor won't download, ping doesn't work (either in terminal or in network tools).  Is there a configuration step that I am missing?  

I have an Atheros 802.11ac Wireless Network Adapter and selected Atheros10 on the install.

**Comment by dma** [comment]
Your system date/time needs to be set to the current date/time UTC. Can you verify that's the case?

**Comment by xmbwd** [comment]
Thanks for the help.  Yes, the system date/time are set to the current date/time (manually).

I also just noticed that pinging the router (e.g., 192.168.1.1) also fails. `nmcli device show` reports all the correct information regarding the device and the network though.   So the network manager is reporting a connection, but it is not able to reach it for some reason.

**Comment by burdges** [comment]
I've noticed this on Dell machines running Debian and its derivatives, but never reliably.  If you can reproduce it reliably then it's should probably be reported upstream.

**Comment by xmbwd** [comment]
I'm on a Lenovo.  Wifi on Ubuntu works (though it has terrible range), as does its derivatives.  Wifi also works in Tails.  But I will do some searches on Debian and Lenovo to see if this is a known issue.

**Comment by xmbwd** [comment]
Thanks @burdges for pointing out that the issue may be Debian-wide.  Turns out there is a terrific guide to fixing this on [linuxquestions.org](https://www.linuxquestions.org/questions/debian-26/howto-install-debian-9-on-lenovo-yoga-910-laptop-4175605249/#post5706154).  The guide says to do it by plugging in an ethernet connection, but I used chroot.  Here is the relevant part for the wifi, please note that the directory and file names are not exactly accurate, and you need to adjust for where you are in your own directory structure and where you downloaded the file.

```
sudo -i
apt-get install curl
curl -L -O https://github.com/kvalo/ath10k-firmware/archive/master.zip
unzip master.zip
mkdir -p /lib/firmware/ath10k/QCA6174/hw3.0/
cp ./ath10k-firmware-master/ath10k/QCA6174/hw3.0/*.bin*  /lib/firmware/ath10k/QCA6174/hw3.0/
cp ./ath10k-firmware-master/ath10k/QCA6174/hw3.0/4.4/*.bin*  /lib/firmware/ath10k/QCA6174/hw3.0/
cd /lib/firmware/ath10k/QCA6174/hw3.0/
cp firmware-4.bin* firmware-5.bin
cp firmware-6.bin* firmware-6.bin
update-initramfs -u
reboot
```

**Comment by xSmurf** [comment]
Closing as resolved.
