### ISSUE TITLE
Xorg grsec help.

### ISSUE THREAD

**Issue by SysCallz** [subgraph/subgraph-os-issues#247]
Get this error in dmesg constantly 
grsec: denied resource overstep by requesting 2048 for RLIMIT_NOFILE against limit 1024 for /usr/lib/xorg/Xorg[Xorg:1289] uid/euid:1000/1000 gid/egid:1000/1000, parent /usr/lib/gdm3/gdm-x-session[gdm-x-session:1287] uid/euid:1000/1000 gid/egid:1000/1000

**Comment by xSmurf** [comment]
RLIMIT can be safely ignored and the warnings will probably be removed in the future.
