### ISSUE TITLE
Chromium Wont open in Oz

### ISSUE THREAD

**Issue by SysCallz** [subgraph/subgraph-os-issues#253]
Chromium will not open when sand-boxed. 
**Version:** 59.0.3071.86-1
**# oz-logs**
un 11 17:24:02 samsung-galaxy-s6 oz-daemon[866]: 2017/06/11 17:24:02 Launch message received. Path: /usr/bin/chromium Name:  Pwd: /home/user Args: []
Jun 11 17:24:02 samsung-galaxy-s6 oz-daemon[866]: 2017/06/11 17:24:02 Execution request from uid 1000, gid 1000
Jun 11 17:24:02 samsung-galaxy-s6 oz-daemon[866]: 2017/06/11 17:24:02 Would launch chromium (ephemeral: %!b(bool=false))
Jun 11 17:24:02 samsung-galaxy-s6 oz-daemon[866]: 2017/06/11 17:24:02 Allowing user: audio (29)
Jun 11 17:24:02 samsung-galaxy-s6 oz-daemon[866]: 2017/06/11 17:24:02 Allowing user: video (44)
Jun 11 17:24:02 samsung-galaxy-s6 oz-daemon[866]: 2017/06/11 17:24:02 [chromium] Init state: &{Profile:{Name:chromium Path:/usr/bin/chromium Paths:[] ProfilePath: DefaultParams:[--disable-background-mode --disa$
Jun 11 17:24:02 samsung-galaxy-s6 oz-daemon[866]: ON_ID] DefaultGroups:[audio video] EtcIncludes:[/etc/alternatives/ /etc/ssl/certs/ /etc/console-setup/ /etc/dbus-1/ /etc/default/locale /etc/fonts/ /etc/gnome/d$
Jun 11 17:24:02 samsung-galaxy-s6 oz-daemon[866]: 2017/06/11 17:24:02 oz-init (chromium) is waiting for init
Jun 11 17:24:02 samsung-galaxy-s6 oz-daemon[866]: 2017/06/11 17:24:02 Configuring bridged networking on bridge 'clear' for chromium (id=1)
Jun 11 17:24:02 samsung-galaxy-s6 oz-daemon[866]: 2017/06/11 17:24:02 Launch of chromium failed: Unable to setup bridged networking: Unable to find unused /16 network
Jun 11 17:24:02 samsung-galaxy-s6 oz-daemon[866]: 2017/06/11 17:24:02 Child process pid=10009 exited from daemon with status -1
Jun 11 17:24:02 samsung-galaxy-s6 oz-daemon[866]: 2017/06/11 17:24:02 No sandbox found with oz-init pid = 10009

**Comment by dma** [comment]
Interesting, I will look into this:

```
Jun 11 17:24:02 samsung-galaxy-s6 oz-daemon[866]: 2017/06/11 17:24:02 Launch of chromium failed: Unable to setup bridged networking: Unable to find unused /16 network
```

**Comment by xSmurf** [comment]
Which version of oz-daemon are you running?

**Comment by SysCallz** [comment]
Version: 0.1.1-1

**Comment by xSmurf** [comment]
This version predates features added for Chromium support. Also what's up with your hostname? That seems like a non standard install...

**Comment by SysCallz** [comment]
I changed it. Its a long story.

**Comment by xSmurf** [comment]
Anyway, chromium nor clearnet will work with this version of OZ which predates both features. Closing.

**Comment by SysCallz** [comment]
I have updated OZ to 0.2.3-2 and it still dose not work. It gives the same error in the logs and Firefox wont sandbox now.
