### ISSUE TITLE
apparmor issues in latest test iso (june 29)

### ISSUE THREAD

**Issue by dma** [subgraph/subgraph-os-issues#257]
Jul 17 22:08:56 subgraph apparmor[15635]: Starting AppArmor profiles:Warning from /etc/apparmor.d/sbin.dhclient (/etc/apparmor.d/sbin.dhclient line 45): Unconfined exec qualifier (ux) allows some dangerous environment variables to be passed to the unconfined process; 'man 5 apparmor.d' for details.
Jul 17 22:08:56 subgraph apparmor[15635]: Warning from /etc/apparmor.d/sbin.dhclient (/etc/apparmor.d/sbin.dhclient line 57): Unconfined exec qualifier (ux) allows some dangerous environment variables to be passed to the unconfined process; 'man 5 apparmor.d' for details.
Jul 17 22:08:56 subgraph apparmor[15635]: AppArmor parser error for /etc/apparmor.d/torbrowser.Browser.firefox in /etc/apparmor.d/torbrowser.Browser.firefox at line 110: Could not open 'local/torbrowser.Browser.firefox'
Jul 17 22:08:56 subgraph apparmor[15635]: AppArmor parser error for /etc/apparmor.d/usr.bin.torbrowser-launcher in /etc/apparmor.d/usr.bin.torbrowser-launcher at line 53: Could not open 'local/usr.bin.torbrowser-launcher'
Jul 17 22:08:56 subgraph apparmor[15635]: Warning from /etc/apparmor.d/sbin.dhclient (/etc/apparmor.d/sbin.dhclient line 45): Unconfined exec qualifier (ux) allows some dangerous environment variables to be passed to the unconfined process; 'man 5 apparmor.d' for details.
Jul 17 22:08:56 subgraph apparmor[15635]: Warning from /etc/apparmor.d/sbin.dhclient (/etc/apparmor.d/sbin.dhclient line 57): Unconfined exec qualifier (ux) allows some dangerous environment variables to be passed to the unconfined process; 'man 5 apparmor.d' for details.
Jul 17 22:08:56 subgraph apparmor[15635]: AppArmor parser error for /etc/apparmor.d/torbrowser.Browser.firefox in /etc/apparmor.d/torbrowser.Browser.firefox at line 110: Could not open 'local/torbrowser.Browser.firefox'
Jul 17 22:08:56 subgraph apparmor[15635]: AppArmor parser error for /etc/apparmor.d/usr.bin.torbrowser-launcher in /etc/apparmor.d/usr.bin.torbrowser-launcher at line 53: Could not open 'local/usr.bin.torbrowser-launcher'

**Comment by mckinney-subgraph** [comment]
AppArmor parser *errors* are serious and have been addressed by releasing a `torbrowser-launcher` 0.2.8 package minus the AppArmor policies (which are not invoked in the Oz sandbox anyhow). 

The *warnings* don't break anything but we should clean up the policy and merge the existing Debian `sbin.dhclient` policies with our own. I will close this issue and make a new one for that specifically.
