### ISSUE TITLE
grsec denied resource overstep

### ISSUE THREAD

**Issue by ghost** [subgraph/subgraph-os-issues#265]
grsec: denied resource overstep by requesting 2048 for RLIMIT_NOFILE against limit 1024 for /usr/lib/xorg/Xorg[Xorg:1315] uid/euid:1000/1000 gid/egid:1000/1000, parent /usr/lib/gdm3/gdm-x-session

**Comment by xSmurf** [comment]
Grsec RLIMIT warnings can be safely ignored. There are plans to patch out logging in the future, closing.
