### ISSUE TITLE
depedency issues with standlone Oz package

### ISSUE THREAD

**Issue by DarkCoridor** [subgraph/subgraph-os-issues#284]
Running stock Debian Stretch and having successfully built `oz-daemon_0.2.4-1_amd64.deb` using the process outlined #282 and trying to install the package I experience the following:

```
user@host:~/subgraph-debian-packages$ sudo dpkg -i /tmp/build-area/oz-daemon_0.2.4-1_amd64.deb 
(Reading database ... 257629 files and directories currently installed.)
Preparing to unpack .../oz-daemon_0.2.4-1_amd64.deb ...
Unpacking oz-daemon (0.2.4-1) over (0.2.4-1) ...
dpkg: dependency problems prevent configuration of oz-daemon:
 oz-daemon depends on oz-profiles; however:
  Package oz-profiles is not installed.
 oz-daemon depends on libgtkgl2.0-1; however:
  Package libgtkgl2.0-1 is not installed.
 oz-daemon depends on arping; however:
  Package arping is not installed.

dpkg: error processing package oz-daemon (--install):
 dependency problems - leaving unconfigured
Processing triggers for rsyslog (8.24.0-1) ...
Errors were encountered while processing:
 oz-daemon
```

**Comment by kibal** [comment]
The ```dpkg``` command doesn't satisfy dependencies. To install oz-daemon with ```dpkg```, one has to install each dependency manually or one may install oz-daemon with ```apt-get``` or ```aptitude``` to satisfy dependencies automatically. Once the dependencies are installed, it is possible to use ```dpkg``` to override the ```oz-daemon``` that is installed with your local package.
