### ISSUE TITLE
document steps to build iso

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#31]
It would be great to be able to build sgos from source - where might we find documentation on how to do this?

**Comment by conorsch** [comment]
Totally this. I assume you've got some packer process behind the scenes, would very much enjoy seeing the moving parts there.

**Comment by mckinney-subgraph** [comment]
So we cleaned up and migrated some stuff from our staging environment into the live-build config. See https://github.com/subgraph/subgraph_desktop_stretch for build instructions. Closing this issue.
