### ISSUE TITLE
Installer fails when run from USB flash drive

### ISSUE THREAD

**Issue by evil5hadow** [subgraph/subgraph-os-issues#329]
I've opened a new issue because an [existing one](https://github.com/subgraph/subgraph-os-issues/issues/143) was closed with no fix:

> Installing Subgraph from a USB drive (ISO written to USB flash drive using Rufus) makes the installer halt on detect and mount CD-ROM.
> 
> "Your installation media couldn't be mounted. This probably means the CD-ROM was not in the drive."

I've tried mount -t vfat /dev/sdb1 /cdrom but the installed failed again.

**Comment by dma** [comment]
Don't use unetbootin or any tools like that to create the livedisk. Use dd from another Linux host.
