### ISSUE TITLE
Confused about Grsecurity

### ISSUE THREAD

**Issue by Zerokami** [subgraph/subgraph-os-issues#340]
I'm confused. 

1) Are you a paying Grsecurity costumer?
If not you better not use the grsecurity name. Use something like coldboot. They will sue you.
Grsecurity is a trademark.

2) Do they still allow redistrubtion under GPL if you are paying them?

3) If you are either using old code or allowed to redistribute under GPL where is the Grsecurity patches source code located?

**Comment by mckinney-subgraph** [comment]
Hello,

We're using the unofficial forward ports, maintained by minipli:
https://github.com/minipli/linux-unofficial_grsec

The source code is available in our apt repo as source packages, ex:
https://devrepo.subgraph.com/subgraph/pool/main/l/linux-4.9.74-subgraph/

**Comment by Zerokami** [comment]
@mckinney-subgraph You might want to use a different name.

Grsecurity doesn't take kindly to freeloaders those who use their Trademark. Trademarks are not covered under GPL.
