### ISSUE TITLE
Auto-login doesn't occur in live mode

### ISSUE THREAD

**Issue by dma** [subgraph/subgraph-os-issues#35]

**Comment by ioerror** [comment]
I can confirm that this is what I see on yesterday's build.

**Comment by mckinney-subgraph** [comment]
Re-enabled:
https://github.com/subgraph/subgraph_desktop_stretch/commit/de4699c282b11666242e19da6d55baef66c5b0ff

It is possibly weird though, some observations:
1. Seems to be many user sessions to close when shutting down/logging out
2. Keyboard input when re-logging in is strange -- need to keep switching back to the password prompt after typing each character (may also be VM related)

Will investigate more.
