### ISSUE TITLE
Oz gnome-shell extension

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#37]
The build I have from two days ago does not come with the little zebra oz shell extension. It should be added to the build.

**Comment by mckinney-subgraph** [comment]
Added to .iso:
https://github.com/subgraph/subgraph_desktop_stretch/commit/006582214ea4363a5dc143bba5dc7c0e7e58052d

Can be installed to old builds w/ `apt-get install gnome-shell-extension-ozshell`.

**Comment by ioerror** [comment]
Confirmed that this is now included in the latest alpha. Hooray - thanks!
