### ISSUE TITLE
Disposable container launching? 

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#38]
In Qubes, it is possible to make a vm template with say, Tor Browser and then launch it a single time, when closed all state is destroyed and in theory, the vm and data is gone forever. It would be awesome if it was possible to do the same with any app, even if it is already configured with some state (eg: a friend wants to use coy for a moment) and to optionally be able to save data, if needed (for say, videos downloaded from a website).

**Comment by xSmurf** [comment]
Moved this to https://github.com/subgraph/oz/issues/15 and closing this particular ticket.
