### ISSUE TITLE
enable apparmor

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#4]
Following https://wiki.debian.org/AppArmor - I have added apparmor by installing the following packages:
```
sudo apt-get install apparmor apparmor-profiles apparmor-utils apparmor-easyprof apparmor-notify apparmor-profiles-extra
```

I enabled it by following the directions on the wiki:
```
sudo perl -pi -e 's,GRUB_CMDLINE_LINUX="(.*)"$,GRUB_CMDLINE_LINUX="$1 apparmor=1 security=apparmor",' /etc/default/grub
sudo update-grub
sudo reboot
```

I then used apparmor to contain dhclient by aa-enabling it.

**Comment by ioerror** [comment]
This works well on the newest alpha iso.

**Comment by xSmurf** [comment]
See also #59

**Comment by mckinney-subgraph** [comment]
Enabled apparmor support:
https://github.com/subgraph/subgraph_desktop_stretch/commit/d5449b79ab0a3425c02c789dd09e09efeb8b88b5
