### ISSUE TITLE
Make transition to SGOS easier

### ISSUE THREAD

**Issue by shiromarieke** [subgraph/subgraph-os-issues#42]
To be able to switch from Debian / Tails to Subgraph OS on a daily basis, here are the programs I would need:
- pond
- xmpp-client by agl
- keepassx
Could you make sure these are installed or protected by Subgraph?

**Comment by mckinney-subgraph** [comment]
Added keepassx to the .iso:
https://github.com/subgraph/subgraph_desktop_stretch/commit/2d3852e94cb374d50a2df86bd0ab950e06ea5501

**Comment by willscott** [comment]
[pond](https://github.com/subgraph/subgraph-os-issues/issues/8)
and
[xmpp-client](https://github.com/subgraph/subgraph-os-issues/issues/19)
are broken out as separate issues.

**Comment by xSmurf** [comment]
KeepassX has been added. As the other two are referenced in separate issues I will close this ticket for now :)
