### ISSUE TITLE
cryptsetup is not installed

### ISSUE THREAD

**Issue by willscott** [subgraph/subgraph-os-issues#48]
causes failure after gnome asks for the encryption password when attempting to mount an encrypted disk

**Comment by dma** [comment]
confirmed, nice catch, thanks

**Comment by mckinney-subgraph** [comment]
Added missing packages:
https://github.com/subgraph/subgraph_desktop_stretch/commit/8d4f7b88e147abca462e838a57f5d1a367d68a07
