### ISSUE TITLE
add coy

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#5]
The default OS should ship with coy (I had to manually install it).

**Comment by mckinney-subgraph** [comment]
Added to .iso:
https://github.com/subgraph/subgraph_desktop_stretch/commit/444f9d105e824f03e86bf6ee6bb3493e00e92b6c

Also in our repository so`apt-get install coyim` should work.

**Comment by ioerror** [comment]
Great - I'm using coyim now and it works pretty well.
