### ISSUE TITLE
Twice now paxrat does *not* set pax flags in paxrat_tbl.conf on new TB firefox binary during first install/run of TBL

### ISSUE THREAD

**Issue by dma** [subgraph/subgraph-os-issues#54]
Result is that Tor Browser does not start due to being killed by PaX. Not sure if this is an intermittent failure of the inotify monitor or something else. Path in paxrat_tbl.conf is correct.

Should be fixed entirely by replacing TBL with a TB package.

**Comment by dma** [comment]
Narrowed down to something happening with paxctl when paxrat service runs and tries to set flags on new / modified binary. Running paxrat manually is workaround: sudo paxrat -c /etc/paxrat/paxrat_tbl.conf.

**Comment by mckinney-subgraph** [comment]
Closing -- there's no further reports of this nor any information to act upon. A separate ticket should be opened for discussing how we will distribute TB in the future in SGOS.
