### ISSUE TITLE
installer issues

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#6]
The installer for the alpha is rough - it touches the network (which it shouldn't) and it does so with a non-grsec kernel. It also failed to ensure my disk was encrypted. It might make sense to pre-seed everything and to ensure it uses the grsec kernel.

**Comment by mckinney-subgraph** [comment]
Network configuration disabled in the installer `preseed.cfg` file:
https://github.com/subgraph/subgraph_desktop_stretch/commit/372c1cd93041ab54cb6317f35914f66de81f8a6f

This means the network is disabled (unless the user manually enables it) during the install, addressing the issue of the installer talking to the network. This also makes it less important for a grsec kernel during the install. 

We're still looking at the fde setup issues. These are theoretically pre-seeded but we've seen the automatic setup fail on real hardware (either not working at all or requiring the user to choose their partitioning scheme).

Ultimately, we will be using another installer that runs from live mode (with grsec kernel and Tor enforcement) so these are just temporary workarounds to make debian-installer less problematic while we still rely on it.

**Comment by mckinney-subgraph** [comment]
Created issue #86 to discuss and fix the FDE problem. Closing this issue since we have address the network access during install problem (which reduces the necessity of grsec kernel during install).
