### ISSUE TITLE
Use apt-transport-tor

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#62]
I think it would be useful if the system apt was Tor aware by using ```apt-transport-tor``` for an apt transport.

**Comment by mckinney-subgraph** [comment]
Added apt-transport-tor to packages:
https://github.com/subgraph/subgraph_desktop_stretch/commit/9ddcac33960e2dae42297773edd5f9dee1504e32

Updated installer `preseed.cfg` to use it for Debian repos (we're still in the process of moving our Subgraph repos but they will also use it):
https://github.com/subgraph/subgraph_desktop_stretch/commit/372c1cd93041ab54cb6317f35914f66de81f8a6f

I am closing this issue and have created a new placeholder issue (#85) to address our short-term and long-term goals for how we will implement the Subgraph apt-repo.
