### ISSUE TITLE
enable support for yubikey

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#68]
First, kill off the ```ssh-agent``` and run ```gpg-agent``` and add udev rules for smartcards/yubi keys.

Subgraph needs to start gpg agent like so:
 ```gpg-agent --enable-ssh-ssupport-daemon```

Then this means that a user can plug in the yubikey and type:
```ssh-add -l```

**Comment by xSmurf** [comment]
Packages added in https://github.com/subgraph/subgraph_desktop_stretch/commit/57b3ce0fcf813997e254c553d549a63fe7023ae1

**Comment by botherder** [comment]
Are those packages enough? I expect you might need to install the relevant udev rules.

**Comment by xSmurf** [comment]
`libccid` definitely installs it's own udev rules at `/lib/udev/rules.d/92-libccid.rules`, I thought the yuibco package did the same but now I'm having doubts, will double check.

@mckinney-subgraph I think we might also want to install libpam-yubico for people who would like to configure their yubikey for pam support.

**Comment by mckinney-subgraph** [comment]
@botherder Yubikey udev rules do get installed at /lib/udev/rules.d/69-yubikey.rules

@xSmurf Added libpam-yubico https://github.com/subgraph/subgraph_desktop_stretch/commit/f86f02a8f18f7d95f3d942e81916f10977a1398d

Now that package dependencies have been added, I am closing this issue and have created a new issue (#84) to cover the configuration needed to make these things work out of the box.
