### ISSUE TITLE
Basic AppArmor profile for subgraph_metaproxy

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#69]
I've written a very basic metaproxy apparmor profile to contain the ```subgraph_metaproxy``` daemon as put into ```/etc/apparmor.d/sbin.subgraph_metaproxy```:
```
# Last Modified: Fri Feb  5 16:34:18 2016
#include <tunables/global>

/sbin/subgraph_metaproxy {
  #include <abstractions/base>

  /etc/subgraph_metaproxy/subgraph_metaproxy.conf r,
  /proc/sys/kernel/hostname r,
  /proc/sys/net/core/somaxconn r,

}
```

Add that file in the correct place and enable it with:
```aa-enforce sbin.subgraph_metaproxy ```

**Comment by mckinney-subgraph** [comment]
This was addressed in the new apparmor-profiles-subgraph package.
