### ISSUE TITLE
 fw-daemon AppArmor profile

### ISSUE THREAD

**Issue by ioerror** [subgraph/subgraph-os-issues#71]
I've written a very basic apparmor profile to contain the fw-daemon as put into ```/etc/apparmor.d/usr.sbin.fw-daemon```
```
# Last Modified: Fri Feb  5 18:40:49 2016
#include <tunables/global>

/usr/sbin/fw-daemon {
  #include <abstractions/base>
  #include <abstractions/ubuntu-konsole>

  capability dac_read_search,
  capability net_admin,
  capability net_raw,

  /etc/nsswitch.conf r,
  /etc/passwd r,
  /etc/protocols r,
  /proc/ r,
  /proc/*/fd/ r,
  /proc/*/net/tcp r,
  /proc/*/net/udp r,
  /proc/sys/net/core/somaxconn r,
  /run/xtables.lock rwk,
  /sbin/xtables-multi rix,
  /usr/share/applications/* r,
  /var/lib/sgfw/sgfw_rules rw,
}
```

Add that file in the correct place and enable it with:
```aa-enforce usr.sbin.fw-daemon```

After rebooting (not required, of course) - I see that it is in enforce mode and the fw ui is working as expected, and the daemon is contained:
```/usr/sbin/fw-daemon (enforce)   root       778  0.0  0.0 673964 11076 ?        Ssl  21:40   0:00 /usr/sbin/fw-daemon```

**Comment by mckinney-subgraph** [comment]
This was addressed in the new apparmor-profiles-subgraph package.
