### ISSUE TITLE
warnings about lack of liferea

### ISSUE THREAD

**Issue by willscott** [subgraph/subgraph-os-issues#90]
the liferea feed reader package appears to not be installed by default. paxrat complains about the lack of the oz link to it when reconfiguring sandboxes after an apt-get change until it is.

**Comment by xSmurf** [comment]
Just to specify this has nothing to do with OZ. Paxrat is there to apply flags for PAX, nothing more, nothing less.

With that said, you're right in that it shouldn't spit out a warning on missing executables.

**Comment by mckinney-subgraph** [comment]
I'll make some changes to the type of output and where it goes soon but this change addresses the issue:
https://github.com/subgraph/paxrat/commit/ebde82d3e7892c94b4ecc5b5818a1de3d1d56f38
(incorporated into paxrat-1.18 package)
