### ISSUE TITLE
$SUBNETS in ferm.conf is forced to /24

### ISSUE THREAD

**Issue by kernel23** [subgraph/subgraph-os-issues#93]
While reading files configuration in /etc/ferm.conf, i realized that all subnets are forged to "/24" (using awk cmd). Values should be read from ip (8) to prevent network issue in some case. Something like this should work ... 

ip -o -f inet addr show | fgrep -v oz0 | awk '/scope global/ {print $4}'

Thanks

**Comment by xSmurf** [comment]
As there are some networks which assign a public IP (universities, CCC camp/congress, etc) we should also make sure that only LAN addresses are ever select. This will require an external script to match the IP to known ranges.

**Comment by mckinney-subgraph** [comment]
This is addressed in subgraph-ferm-config 0.8 package. The code to calculate the LAN exception in the ferm config is this:
@def $SUBNETS = (`ip -o -f inet addr show | fgrep -v oz0 | awk '/scope global/ {print $4}' | grep -E '^(192\.168|10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.)' || echo ''`);
