### ISSUE TITLE
mouse cursor does not move when run in QEMU

### ISSUE THREAD

**Issue by prusnak** [subgraph/subgraph-os-issues#95]
I downloaded `release_20160222_1.iso` and tried to run it in QEMU (that's how I usually test various builds of ISOs first) using the following:

```
qemu-kvm -m 2048 -cdrom release_20160222_1.iso
```

GNOME Shell starts fine, but the mouse cursor is not moving.

This worked in older `release_02032016_1.iso`.

**Comment by dma** [comment]
Hey, this is a known issue introduced into stretch very recently with xorg package updates. We expect it to be fixed soon. It also affects VMWare Fusion.

**Comment by xSmurf** [comment]
This is apparently fixed upstream, @prusnak any chance you can test with the alpha release and report back/close the issue if it has?

**Comment by prusnak** [comment]
I confirm that issue is fixed. Thanks! Closing ...
