### ISSUE TITLE
hexchat can't resolve hostnames

### ISSUE THREAD

**Issue by willscott** [subgraph/subgraph-os-issues#99]
When connecting in HexChat, the program seems to fail to complete DNS resolution

```
Looking up irc.oftc.net
Unknown host. Maybe you misspelled it?
Cycling to next server in OFTC...
Disconnected ()
```

**Comment by xSmurf** [comment]
Hi will, can you try to add a socket to the dns resolver to the profile? something like:

{"type":"client", "proto":"udp", "port":53}

**Comment by willscott** [comment]
where does that profile live?

**Comment by burdges** [comment]
I think this was never actually fixed
